#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -l walltime=048:00:00
#PBS -l select=8:ncpus=32:mpiprocs=32
#PBS -l place=scatter:excl
#PBS -q standard
#PBS -N dtmb
#PBS -j oe
#PBS -l application=proteus
#PBS -V
#PBS -m eba
#PBS -M cekees@gmail.com
#setup modules and check proteus version
#. /opt/cray/pe/modules/default/etc/modules.sh
#export MODULEPATH=/p/app/unsupported/proteus/modulefiles:${MODULEPATH}
#module load proteus/master
#which parun
#create a working directory and copy over the inputs use
cd $PBS_O_WORKDIR
mkdir $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
cp dtmb.* $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
cp genmesh $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
#change into the work directory and run
cd  $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
aprun -n 1 ./genmesh dtmb 0.1
aprun -n ${BC_MPI_TASKS_ALLOC}  parun -F -l 5 --TwoPhaseFlow dtmb.py -C "skip_gmsh=True he=0.1 speed=5.0"
