#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -l walltime=001:00:00
#PBS -l select=4:ncpus=44:mpiprocs=44
#PBS -l place=scatter:excl
#PBS -q debug
#PBS -N floodwall3D
#PBS -j oe
#PBS -l application=proteus
#PBS -V
#PBS -m eba
##PBS -M myemail@mydomain
#setup modules and check proteus version
. /opt/cray/pe/modules/default/etc/modules.sh
export MODULEPATH=/p/app/unsupported/proteus/modulefiles:${MODULEPATH}
module load proteus/master
which parun
#create a working directory and copy over the inputs use
cd $PBS_O_WORKDIR
mkdir $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
cp floodwall.py $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
cp floodwall.pbs $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
#change into the work directory and run
cd  $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
aprun -n ${BC_MPI_TASKS_ALLOC}  parun -F -l 5 --TwoPhaseFlow floodwall.py -C "he=0.0125"
