#!/usr/bin/env python
import sys
from subprocess import check_call
from proteus import MeshTools as mt, Profiling, Comm
filebase = sys.argv[1]
he = float(sys.argv[2])
comm = Comm.init()
Profiling.procID=comm.rank()
Profiling.openLog(filebase+"_genmesh.log",11,".")
Profiling.verbose=True
Profiling.logEvent("Starting mesh generation with gmsh")
gmsh_cmd = "gmsh {0:s} -v 10 -3 -o {1:s} -format msh2 -clmax {2:e}".format(filebase+".geo", filebase+".msh",he)
check_call(gmsh_cmd, shell=True)
Profiling.logEvent("Finished running mesh generation with gmsh")
Profiling.logEvent("Converting gmsh msh2 format to TetGen format")
mt.msh2simplex(filebase, nd=3)
Profiling.logEvent("Generating full edge information in TetGen format")
check_call("tetgen -Vfeen {0:s}.ele".format(filebase), shell=True)
check_call("mv {0:s}.1.ele {0:s}.ele".format(filebase), shell=True)
check_call("mv {0:s}.1.node {0:s}.node".format(filebase), shell=True)
check_call("mv {0:s}.1.face {0:s}.face".format(filebase), shell=True)
check_call("mv {0:s}.1.neigh {0:s}.neigh".format(filebase), shell=True)
check_call("mv {0:s}.1.edge {0:s}.edge".format(filebase), shell=True)
Profiling.logEvent("Done!")
