#!/bin/bash
#$ -V                    #Inherit the submission environment
#$ -cwd                  # Start job in submission directory
#$ -N proteus              # Job Name
#$ -j y                  # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID # Name of the output file (eg. myMPI.oJobID)
#$ -pe 12way 24          # Requests 12 tasks/node, 24 cores total
#$ -q development             # Queue name normal
#$ -l h_rt=00:30:00      # Run time (hh:mm:ss) - 1.5 hours
#$ -M cekees@gmail.com                    # Use email notification address
#$ -m be                 # Email at Begin and End of job
set -x                   # Echo commands, use set echo with csh
export MV2_ON_DEMAND_THRESHOLD=2048
cd ${PROTEUS}/proteusModule/test
ibrun tacc_affinity ${PROTEUS_PYTHON} test_import.py
ibrun tacc_affinity ${PROTEUS_PYTHON} test_poisson.py
