#!/bin/bash
#PBS -l select=16:ncpus=32:mpiprocs=32
#PBS -A ERDCV00898R40
#PBS -l walltime=001:00:00
#PBS -q debug
#PBS -N testProteus
#PBS -j oe
#PBS -l application=proteus

source /opt/modules/default/init/bash
module swap PrgEnv-pgi PrgEnv-gnu
module unload xt-libsci
module load acml
PROTEUS_PYTHON=$(which python)
#source ${PROTEUS}/envConfig/garnet.gnu.bash

cd $PBS_O_WORKDIR
export MPICH_RANK_REORDER_METHOD=2
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing import"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
#export LD_DEBUG=all
aprun -n 1 -N 1 ${PROTEUS_PYTHON} -v test_import.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing import on all mpi  processes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 512 -N 32 ${PROTEUS_PYTHON} test_import.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing poisson 1 way on 1 nodes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 1 -N 1 ${PROTEUS_PYTHON} test_meshPartitionFromTetgenFiles.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing poisson 32 way on 2 nodes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 64 -N 32 ${PROTEUS_PYTHON} test_meshPartitionFromTetgenFiles.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing poisson 16 way on 2 nodes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 32 -N 16 ${PROTEUS_PYTHON} test_meshPartitionFromTetgenFiles.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing poisson 12 way on 2 nodes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 24 -N 12 ${PROTEUS_PYTHON} test_meshPartitionFromTetgenFiles.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing poisson 8 way on 2 nodes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 16 -N 8 ${PROTEUS_PYTHON} test_meshPartitionFromTetgenFiles.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "testing poisson 32 way on 16 nodes"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
aprun -n 512 ${PROTEUS_PYTHON} test_meshPartitionFromTetgenFiles.py
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "done with test_proteus_garnet"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
