#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -l walltime=012:00:00
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -l place=scatter:excl
#PBS -q standard
#PBS -N weir
#PBS -j oe
#PBS -l application=proteus
#PBS -m eba
##PBS -M myemail@mydomain
#setup modules and check proteus version
#. ${MODULESHOME}/etc/modules.sh
#export MODULEPATH=${PROJECTS_HOME}/proteus/modulefiles:${MODULEPATH}
#module load proteus/1.7.0
which parun
#create a working directory and copy over the inputs use
cd $PBS_O_WORKDIR
mkdir $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
cp broad_crested_weir.py $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
cp broad_crested_weir.pbs $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
#change into the work directory and run
cd  $WORKDIR/$PBS_JOBNAME.$PBS_JOBID
aprun -n ${BC_MPI_TASKS_ALLOC}  parun -l 5 --TwoPhaseFlow broad_crested_weir.py -C "he=0.01625"
