#!/bin/csh                                                                                         
#PBS -A ERDCV00898ENQ                                                                              
#PBS -l walltime=1:00:00                                                                          
#PBS -l select=1:ncpus=44:mpiprocs=44                                                              
#PBS -l place=scatter:excl                                                                         
#PBS -q debug                                                                                   
#PBS -N template                                                                                         
#PBS -j oe                                                                                         
#PBS -l application=proteus                                                                        
#PBS -V                                                                                            
#PBS -m eba                                                                                                    
                                                                                       
cd $PBS_O_WORKDIR
mkdir $WORKDIR/training/template.$PBS_JOBID
cp template_st.py $WORKDIR/training/template.$PBS_JOBID
cp debug.pbs $WORKDIR/training/template.$PBS_JOBID
cd $WORKDIR/training/template.$PBS_JOBID

#aprun -n ${BC_MPI_TASKS_ALLOC} parun --TwoPhaseFlow -f template_st.py -l 5 -F -C "he=0.005" -D test
aprun -n 1 parun --TwoPhaseFlow -f template_st.py -l 5 -F -C "he=0.005" -D test
