language: python
env:
- TEST_PROFILE="test.proteus.yaml"
python:
- 2.7
before_install:
- sudo apt-get update -qq
- sudo apt-get install gfortran pv cmake swig libblas-dev liblapack-dev
install:
- git clone https://github.com/erdc-cm/proteus
script:
- set -o pipefail
- make check 2>&1 | pv -i 15 -n | cat > log.txt
- tail -n 60 log.txt
notifications:
email: false
