# This profile file controls your <#> (HashDist) build environment.

# In the future, we'll provide better incorporation of
# automatic environment detection.  For now, have a look
# at the YAML files in the top-level directory and choose
# the most *specific* file that matches your environment.

extends:
- file: debian.yaml

# The packages list specifies all the packages that you
# require installed.  <#> will ensure that all packages
# and their dependencies are installed when you build this
# profile.

packages:

  launcher:
#  cmake:
#    use: host-cmake
  python:
    host: false
    link: shared
    build_with: |
      bzip2, sqlite
  blas:
    use: host-blas
#  daetk:
  mpi:
    use: mpich
#  mpi4py:
#  nose:
#  hdf5:
  petsc:
    build_with: |
      parmetis
    coptflags: -O2
    link: shared
    debug: false
#  petsc4py:
#    with_conf: true
#  pytables:
#  superlu:
#  tetgen:
#  triangle:
