# This profile file controls your <#> (HashDist) build environment.

# In the future, we'll provide better incorporation of
# automatic environment detection.  For now, have a look
# at the YAML files in the top-level directory and choose
# the most *specific* file that matches your environment.

extends:
- file: debian.yaml

# The packages list specifies all the packages that you
# require installed.  <#> will ensure that all packages
# and their dependencies are installed when you build this
# profile.

packages:
  clawpack:
  launcher:
  cmake:
    use: host-cmake
  python:
    host: false
    link: shared
    build_with: |
      bzip2, sqlite
  blas:
    use: host-blas
  lapack:
    use: host-lapack
  daetk:
  mpi:
    use: mpich
  mpi4py:
  nose:
  coverage:
  hdf5:
  matplotlib:
  petsc:
    build_with: |
      parmetis
    download: |
      superlu, superlu_dist, spooles, hypre, blacs, scalapack, mumps
    coptflags: -O2
    link: shared
    debug: false
  petsc4py:
    with_conf: true
  pillow:
  pytables:
  sphinx:
  superlu:
  sympy:
  tetgen:
  triangle:
  memory_profiler:
  boost:
    toolset: gcc
    address_model: 64
    build_with: |
      python
  netcdf4:
  python-netcdf4:
  netcdf4f:
  netcdf4cpp:
  jasper:
  grib_api:
  pyproj:
  pygrib:
  scipy:
  ipython:
  terminado:
  h5py:
  pydap:
  leafletwidget:
  geojson:
  rdp:
  rtree:
  ode:
  ipdb:
  pip:
  pexpect:
