#!/usr/bin/env bash
if [ "$SAGE_LOCAL" = "" ]; then
   echo "SAGE_LOCAL undefined ... exiting";
   echo "Maybe run 'sage -sh'?"
   exit 1
fi

export PROTEUS_PREFIX=${SAGE_LOCAL}
export PROTEUS_PYTHON=${SAGE_LOCAL}/bin/python
export PROTEUS=${SAGE_ROOT}/spkg/build/proteus
export DAETK_DIR=${SAGE_ROOT}/spkg/build/proteus/externalPackages/daetk
export PETSC_DIR=${SAGE_ROOT}/spkg/build/proteus/externalPackages/petsc-3.1-p1
echo ${PROTEUS_PREFIX}
echo ${PROTEUS_PYTHON}
echo ${PROTEUS}
echo ${DAETK_DIR}
ls ${DAETK_DIR}
echo ${PETSC_DIR}
ls ${PETSC_DIR}

cd externalPackages

numpy=`cd $SAGE_ROOT/spkg/standard/; ./newest_version numpy`
if [ $? -ne 0 ]; then
    echo "Failed to find numpy.  Installing numpy"
    make install_numpy
    if [ $? -ne 0 ]; then
       echo "Error building numpy."
       exit 1
    fi
else
    echo "Found numpy"
fi

cython=`cd $SAGE_ROOT/spkg/standard/; ./newest_version cython`
if [ $? -ne 0 ]; then
    echo "Failed to find cython.  Installing cython"
    make install_cython
    if [ $? -ne 0 ]; then
       echo "Error building cython."
       exit 1
    fi
else
    echo "Found cython"
fi

tables=`cd $SAGE_ROOT/spkg/standard/; ./newest_version tables`
if [ $? -ne 0 ]; then
    echo "(Py)tables not installed. Installing tables"
    make  install_tables
    if [ $? -ne 0 ]; then
       echo "Error building tables."
       exit 1
    fi
else
    echo "Found tables"
fi
make install_tables

mpi4py=`cd $SAGE_ROOT/spkg/standard/; ./newest_version mpi4py`
if [ $? -ne 0 ]; then
    echo "mpi4py not installed. Installing mpi4py"
    make install_mpi4py
    if [ $? -ne 0 ]; then
       echo "Error building mpi4py."
       exit 1
    fi
else
    echo "Found mpi4py"
fi
make install_mpi4py

petsc4py=`cd $SAGE_ROOT/spkg/standard/; ./newest_version petsc4py`
if [ $? -ne 0 ]; then
    echo "petsc4py not installed. Installing petsc4py"
    make install_pestc4py
    if [ $? -ne 0 ]; then
       echo "Error building petsc."
       exit 1
    fi
fi
make install_petsc4py

make install_triangle
if [ $? -ne 0 ]; then
   echo "Error building triangle."
   exit 1
else
    echo "Found triangle"
fi

make install_tetgen
if [ $? -ne 0 ]; then
   echo "Error building tetgen."
   exit 1
fi

make install_superlu
if [ $? -ne 0 ]; then
   echo "Error building superlu."
   exit 1
fi

make install_daetk
if [ $? -ne 0 ]; then
   echo "Error building daetk."
   exit 1
fi

cd ..
export FC=sage_fortran
export F77=sage_fortran
export F90=sage_fortran
export CC=mpicc
export CXX=mpicxx
make install_proteusModule
if [ $? -ne 0 ]; then
   echo "Error building proteusModule."
   exit 1
fi
