#PBS -A erdcvenq
#PBS -l walltime=48:00:00
#PBS -l ncpus=128
#PBS -q standard
#PBS -N adh.container3d
#PBS -j oe
#PBS -m be
#PBS -M cekees@gmail.com
#PBS -o adh.container3d
#PBS -S /bin/tcsh
#PBS -V
mkdir $WORKDIR/container3d.$PBS_JOBID
cd $PBS_O_WORKDIR
aprun -n 128 python $PYADH/pyadhModule/scripts/parun container_so.py -l 3 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package superlu_dist"  -D $WORKDIR/container3d.$PBS_JOBID

