#!/bin/tcsh 			  
#BSUB -J cylinder2d_us
#BSUB -o out.cylinder2d_us.%J   
#BSUB -e err.cylinder2d_us.%J   
#BSUB -n 1 -W 0:10
#BSUB -q development
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
echo "-ksp_type gmres -pc_type asm -ksp_rtol 0.0 -ksp_atol 1.0e-10" > petsc_options.cylinder2d_us.txt
ibrun python ../../scripts/parun navier_stokes_cylinder_2d_p.py navier_stokes_cylinder_2d_c0p1c0p1_n.py -l 3 -v -O petsc_options.cylinder2d_us.txt

