#!/bin/tcsh              
#$ -V                     # Inherit the submission environment
#$ -cwd                   # Start job in  submission directory
#$ -N cylinder2d               # Job Name
#$ -j y                   # combine stderr & stdout into stdout    
#$ -o $JOB_NAME.o$JOB_ID  # Name of the output file (eg. myMPI.oJobID)
#$ -pe 16way 32           # Requests 16 cores/node, 32 cores total
#$ -q development              # Queue name
#$ -l h_rt=00:30:00       # Run time (hh:mm:ss) - 1.5 hours
#$ -M cekees@gmail.com      # Email notification address (UNCOMMENT)
## -m be                  # Email at Begin/End of job  (UNCOMMENT)
ibrun python ../../scripts/parun navier_stokes_cylinder_2d_p.py navier_stokes_cylinder_2d_c0p1c0p1_n.py -l 3 -v -P "-pc_type lu -pc_factor_mat_solver_package spooles"

