#PBS -A erdcvc2w
#PBS -l walltime=6:00:00
#PBS -l ncpus=16
#PBS -q challenge
#PBS -N adh.damBreak2d
#PBS -j oe
env
which python
echo $PYTHONPATH
mkdir $WORKDIR/damBreak2d.$PBS_JOBID
cd $PBS_O_WORKDIR
#aprun -n 32 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_damBreak_2d_so.py -s -l 0 -v -P "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-8 -ksp_monitor"  -D $WORKDIR/damBreak2d.$PBS_JOBID
aprun -n 16 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_damBreak_2d_so.py -s -l 4 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/damBreak2d.$PBS_JOBID
cd $WORKDIR
tar czvf damBreak2d.$PBS_JOBID.tar.gz damBreak2d.$PBS_JOBID
mv -f damBreak2d.$PBS_JOBID.tar.gz $HOME
#rm -rf damBreak2d.$PBS_JOBID
