#PBS -A erdcvc2w
#PBS -l walltime=1:00:00
#PBS -l ncpus=1
#PBS -q challenge
#PBS -N adh.vessel3d
#PBS -j oe
env
which python
echo $PYTHONPATH
mkdir $WORKDIR/gf_3d.$PBS_JOBID
cd $PBS_O_WORKDIR
#aprun -n 512 python $PYADH/pyadhModule/scripts/parun navier_stokes_gf_3d_so.py -s -l 1 -v -P "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-8 -ksp_monitor"  -D $WORKDIR/gf_3d.$PBS_JOBID
#aprun -n 256 python $PYADH/pyadhModule/scripts/parun navier_stokes_gf_3d_p.py navier_stokes_gf_3d_n.py -s -l 5 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/gf_3d.$PBS_JOBID
aprun -n 1 python $PYADH/pyadhModule/scripts/parun navier_stokes_gf_3d_p.py navier_stokes_gf_3d_n.py -s -l 5 -v -P "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-10 -ksp_monitor" -D $WORKDIR/gf_3d.$PBS_JOBID
cd $WORKDIR
tar czvf gf_3d.$PBS_JOBID.tar.gz gf_3d.$PBS_JOBID
mv -f gf_3d.$PBS_JOBID.tar.gz $HOME
#rm -rf gf_3d.$PBS_JOBID
