#!/bin/tcsh 			  
#BSUB -J re_ipars_case1
#BSUB -e err.%J
#BSUB -o out.%J   
#BSUB -n 8
#BSUB -W 0:30
#BSUB -q development
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
echo "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles" > petsc.re_ipars_case1.options
#echo "-log_trace -info -malloc -help" > petsc.options
ibrun parun re_ipars_case1_3d_p.py re_ipars_case1_3d_c0p1_n.py -l 3 -v -O petsc.re_ipars_case1.options

