#PBS -A erdcvenq
#PBS -l walltime=48:00:00
#PBS -l select=2:ncpus=8:mpiprocs=8
#PBS -l place=scatter:excl
#PBS -q standard
#PBS -N adh.wigley3d
#PBS -j oe
echo $LD_LIBRARY_PATH
mkdir $WORKDIR/wigley3d.$PBS_JOBID
setenv MPI_GROUP_MAX 1024
cd $PBS_O_WORKDIR
mpiexec_mpt -np 16  python2.6-mpi $PYADH/pyadhModule/scripts/parun wigley_so.py -l 3 -v -P "-ksp_type bcgsl -pc_type asm  -pc_asm_type basic -sub_ksp_type preonly -sub_pc_type lu -sub_pc_factor_mat_solver_package superlu -ksp_rtol 0.0 -ksp_atol 1.0e-10 -ksp_monitor_true_residual"  -D $WORKDIR/wigley3d.$PBS_JOBID
#mpiexec_mpt -np 16  python2.6-mpi $PYADH/pyadhModule/scripts/parun wigley_so.py -l 3 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package superlu_dist"  -D $WORKDIR/wigley3d.$PBS_JOBID
#mpiexec_mpt -np 16  python2.6-mpi $PYADH/pyadhModule/scripts/parun wigley_so.py -l 3 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/wigley3d.$PBS_JOBID
cd $WORKDIR
tar czvf wigley3d.$PBS_JOBID.tar.gz wigley3d.$PBS_JOBID
mv -f wigley3d.$PBS_JOBID.tar.gz $HOME
