#!/usr/bin/env python
import sys,os,pexpect,time

np=16
qcmduninstall = "idev -uninstall"
qcmd="idev -pe 16 %(np)i -t 00:10:00" %  {"np":np}
PROTEUS = os.getenv('PROTEUS')
PROTEUS_PYTHON = os.getenv('PROTEUS_PYTHON')
pcmd="ibrun %(PROTEUS_PYTHON)s %(PYTHON_SCRIPT)s" % {"np":np,
                                                                "PROTEUS":PROTEUS,
                                                                "PROTEUS_PYTHON":PROTEUS_PYTHON,
                                                                "PYTHON_SCRIPT":sys.argv[1]}
child = pexpect.spawn(qcmduninstall)
child = pexpect.spawn(qcmd,timeout=30*60)
child.logfile = sys.stdout
index = child.expect(["May I insert the commands?",pexpect.TIMEOUT],timeout=10)
if index == 0:
    child.sendline("yes")
index = child.expect(["job status: r","job status: Eqw",pexpect.TIMEOUT],timeout=30*60)
if index == 0:
    time.sleep(10)
    index2 = child.expect(["Are you sure you want to continue connecting (yes/no)?",pexpect.TIMEOUT],timeout=10)
    if index2 == 0:
        child.sendline("yes")
    time.sleep(10)
    child.sendline(pcmd)
    child.expect(["PEXPECT_EXIT",pexpect.EOF,pexpect.TIMEOUT],timeout=10*60)
    child.sendline("exit")
child.close()

