#!/usr/bin/env python
import sys,os,pexpect

np=32
qcmd="qsub -l ccm=1 -l ncpus=%(np)i -A ERDCV00898ENQ -l walltime=001:00:00 -q debug -l application=proteus -I" %  {"np":np}
PROTEUS = os.getenv('PROTEUS')
PROTEUS_PYTHON = os.getenv('PROTEUS_PYTHON')

pcmd="aprun -n %(np)i %(PROTEUS_PYTHON)s %(PYTHON_SCRIPT)s" % {"np":np,
                                                                "PROTEUS":PROTEUS,
                                                                "PROTEUS_PYTHON":PROTEUS_PYTHON,
                                                                "PYTHON_SCRIPT":sys.argv[1]}
child = pexpect.spawn(qcmd,timeout=30*60)
child.logfile = sys.stdout
child.expect("CCM Start success")
child.sendline(pcmd)
child.expect(["PEXPECT_EXIT",pexpect.EOF,pexpect.TIMEOUT],timeout=10*60)
child.sendline("exit")
child.close()

