#!/usr/bin/env python
import sys,os,pexpect

np=2
PROTEUS = os.getenv('PROTEUS')
PROTEUS_PYTHON = os.getenv('PROTEUS_PYTHON')
print sys.argv
pcmd="mpirun -n %(np)i %(PROTEUS_PYTHON)s %(PYTHON_SCRIPT)s" % {"np":np,
                                                                "PROTEUS":PROTEUS,
                                                                "PROTEUS_PYTHON":PROTEUS_PYTHON,
                                                                "PYTHON_SCRIPT":sys.argv[1]}
child = pexpect.spawn('/bin/bash',timeout='5')
child.logfile = sys.stdout
child.sendline(pcmd)
child.expect(["PEXPECT_EXIT",pexpect.EOF,pexpect.TIMEOUT],timeout=10*60)
child.sendline("exit")
child.kill()
