#!/usr/bin/env python
import sys,os,pexpect

np=24
qcmd="idev -pe 12 %(np)i -t 01:00:00" %  {"np":np}
PROTEUS = os.getenv('PROTEUS')
PROTEUS_PYTHON = os.getenv('PROTEUS_PYTHON')
pcmd="aprun -n %(np)i %(PROTEUS_PYTHON)s %(PYTHON_SCRIPT)s" % {"np":np,
                                                                "PROTEUS":PROTEUS,
                                                                "PROTEUS_PYTHON":PROTEUS_PYTHON,
                                                                "PYTHON_SCRIPT":sys.argv[1]}
child = pexpect.spawn(qcmd,timeout=60*60)
child.logfile = sys.stdout
child.expect("read")
child.sendline(pcmd)
child.expect("PEXPECT_EXIT")
child.sendline("exit")
