var searchData=
[
  ['kepsilon_5f2d_5fevaluate',['kEpsilon_2D_Evaluate',['../group__transport_coefficients.html#ga32efe4105830fcb732281e813141148a',1,'kEpsilon_2D_Evaluate(int nPoints, int nSpace, double sigma_k, double sigma_e, double c_1, double c_2, double c_mu, double c_e, double nu, double *velocity, double *gradu, double *gradv, double *k, double *epsilon, double *m_k, double *dm_k, double *m_e, double *dm_e, double *phi_k, double *dphi_k, double *phi_e, double *dphi_e, double *f_k, double *df_k, double *f_e, double *df_e, double *a_k, double *da_k_dk, double *da_k_de, double *a_e, double *da_e_dk, double *da_e_de, double *r_k, double *dr_k_dk, double *dr_k_de, double *r_e, double *dr_e_dk, double *dr_e_de):&#160;transportCoefficients.c'],['../group__transport_coefficients.html#ga32efe4105830fcb732281e813141148a',1,'kEpsilon_2D_Evaluate(int nPoints, int nSpace, double sigma_k, double sigma_e, double c_1, double c_2, double c_mu, double c_e, double nu, double *velocity, double *gradu, double *gradv, double *k, double *epsilon, double *m_k, double *dm_k, double *m_e, double *dm_e, double *phi_k, double *dphi_k, double *phi_e, double *dphi_e, double *f_k, double *df_k, double *f_e, double *df_e, double *a_k, double *da_k_dk, double *da_k_de, double *a_e, double *da_e_dk, double *da_e_de, double *r_k, double *dr_k_dk, double *dr_k_de, double *r_e, double *dr_e_dk, double *dr_e_de):&#160;transportCoefficients.c']]],
  ['kepsilon_5f2d_5fevaluate_5fsd',['kEpsilon_2D_Evaluate_sd',['../transport_coefficients_8c.html#ae8616dc65f89c84bbdaafd712872ef0b',1,'transportCoefficients.c']]],
  ['kepsilon_5f3d_5fevaluate',['kEpsilon_3D_Evaluate',['../transport_coefficients_8c.html#ad159a0e74a01e7dcaa71c59ba5523759',1,'transportCoefficients.c']]],
  ['kepsilon_5f3d_5fevaluate_5fsd',['kEpsilon_3D_Evaluate_sd',['../transport_coefficients_8c.html#a550adfb198d075b03e833c9f95f49455',1,'transportCoefficients.c']]],
  ['kepsilon_5fepsilon_5f2d_5fevaluate_5fsd',['kEpsilon_epsilon_2D_Evaluate_sd',['../transport_coefficients_8c.html#a7bb10bdb9e96c27d96ab7d20c237c57c',1,'transportCoefficients.c']]],
  ['kepsilon_5fepsilon_5f3d_5fevaluate_5fsd',['kEpsilon_epsilon_3D_Evaluate_sd',['../transport_coefficients_8c.html#a103fe134ab4cbb641a93b5732a9956de',1,'transportCoefficients.c']]],
  ['kepsilon_5fk_5f2d_5fevaluate_5fsd',['kEpsilon_k_2D_Evaluate_sd',['../transport_coefficients_8c.html#a925895da7fd0b5d45a65fdfcef5789f5',1,'transportCoefficients.c']]],
  ['kepsilon_5fk_5f3d_5fevaluate_5fsd',['kEpsilon_k_3D_Evaluate_sd',['../transport_coefficients_8c.html#ac0071af0ab2ab4e5af03648fd6ede50b',1,'transportCoefficients.c']]]
];
