import os
from default import *


PROTEUS_MPI_INCLUDE_DIR='/apps/openmpi/1.10.2/gcc/6.1.0/include'
PROTEUS_MPI_LIB_DIR = '/apps/openmpi/1.10.2/gcc/6.1.0/lib'
PROTEUS_MPI_INCLUDE_DIRS = [PROTEUS_MPI_INCLUDE_DIR]
PROTEUS_MPI_LIB_DIRS = [PROTEUS_MPI_LIB_DIR]
PROTEUS_MPI_LIBS =[]
PROTEUS_LAPACK_LIB_DIR = PROTEUS_LIB_DIR
