from .default import *

PROTEUS_MPI_INCLUDE_DIR = "/usr/local/packages/mpich/3.4.2/s3bq4iw/include"
PROTEUS_MPI_LIB_DIR = "/usr/local/packages/mpich/3.4.2/s3bq4iw/lib"
PROTEUS_MPI_INCLUDE_DIRS = [PROTEUS_MPI_INCLUDE_DIR]
PROTEUS_MPI_LIB_DIRS = [PROTEUS_MPI_LIB_DIR]
PROTEUS_SCOREC_LIB_DIRS += PROTEUS_MPI_LIB_DIRS
PROTEUS_SCOREC_INCLUDE_DIRS += PROTEUS_MPI_INCLUDE_DIRS
