#PBS -A erdcvc2w
#PBS -l walltime=12:00:00
#PBS -l ncpus=64
#PBS -q challenge
#PBS -N adh.bubble2d
#PBS -j oe
env
which python
echo $PYTHONPATH
mkdir $WORKDIR/bubble2d.$PBS_JOBID
cd $PBS_O_WORKDIR
#aprun -n 32 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_bubble_2d_so.py -s -l 0 -v -P "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-8 -ksp_monitor"  -D $WORKDIR/bubble2d.$PBS_JOBID
aprun -n 64 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_bubble_2d_so.py -s -l 4 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/bubble2d.$PBS_JOBID
cd $WORKDIR
tar czvf bubble2d.$PBS_JOBID.tar.gz bubble2d.$PBS_JOBID
mv -f bubble2d.$PBS_JOBID.tar.gz $HOME
#rm -rf bubble2d.$PBS_JOBID
