#!/bin/tcsh 			  
#BSUB -J cavity3d
#BSUB -o oe.cavity3d.%J   
#BSUB -e oe.cavity3d.%J   
#BSUB -n 32 -W 48:00
#BSUB -q normal
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
#echo "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-7" > petsc_options.cavity3d.txt
echo "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles" > petsc_options.cavity3d.txt
ibrun python ../../scripts/parun navier_stokes_cavity_3d_p.py navier_stokes_cavity_3d_c0p1c0p1_n.py -l 3 -v -O petsc_options.cavity3d.txt

