#!/bin/tcsh 			  
#BSUB -J container
#BSUB -e err.container.%J
#BSUB -o out.container.%J
#BSUB -n 128
#BSUB -W 48:00
#BSUB -q normal
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
echo "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package superlu_dist" > petsc.container.options
ibrun parun_mpi container_so.py -l 3 -v -O petsc.container.options

