#!/bin/tcsh 			  
#BSUB -J cylinder2d
#BSUB -o oe.cylinder2d.%J   
#BSUB -e oe.cylinder2d.%J   
#BSUB -n 128 -W 12:00
#BSUB -q normal
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
echo "-ksp_type gmres -pc_type asm -ksp_rtol 0.0 -ksp_atol 1.0e-7" > petsc_options.cylinder2d.txt
ibrun python ../../scripts/parun navier_stokes_cylinder_2d_p.py navier_stokes_cylinder_2d_c0p1c0p1_n.py -l 3 -v -O petsc_options.cylinder2d.txt

