#PBS -A erdcvenq
#PBS -l walltime=6:00:00
#PBS -l ncpus=128
#PBS -q standard
#PBS -N adh.vessel3d
#PBS -j oe
mkdir $WORKDIR/gf_3d.$PBS_JOBID
cd $PBS_O_WORKDIR
#aprun -n 512 python $PYADH/pyadhModule/scripts/parun navier_stokes_gf_3d_so.py -s -l 1 -v -P "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-8 -ksp_monitor"  -D $WORKDIR/gf_3d.$PBS_JOBID
#aprun -n 256 python $PYADH/pyadhModule/scripts/parun navier_stokes_gf_3d_p.py navier_stokes_gf_3d_n.py -s -l 5 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/gf_3d.$PBS_JOBID
aprun -n 128 python $PYADH/pyadhModule/scripts/parun navier_stokes_gf_3d_p.py navier_stokes_gf_3d_n.py -l 3 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package superlu_dist" -D $WORKDIR/gf_3d.$PBS_JOBID
