#!/bin/tcsh 			  
#BSUB -J gw_het_utep_2d
#BSUB -e err.gw_het_utep_2d.%J
#BSUB -o out.gw_het_utep_2d.%J   
#BSUB -n 16
#BSUB -W 0:10
#BSUB -q development
echo $LD_LIBRARY_PATH
echo $PYTHONPATH
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
echo "-ksp_atol 1.0e-8 -ksp_rtol 1.0e-8" > petsc.gw_het_utep_2d.options
ibrun parun gw_het_utep_2d_p.py gw_het_utep_2d_c0p1_par_n.py -l 3 -v -O petsc.gw_het_utep_2d.options

