#!/bin/tcsh 			  
#BSUB -J re_vgm_sand_10x10x10_3d
#BSUB -e err.re_vgm_sand_10x10x10_3d.%J
#BSUB -o out.re_vgm_sand_10x10x10_3d.%J   
#BSUB -n 256
#BSUB -W 12:00
#BSUB -q normal
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
#echo "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles" > petsc.re_vgm_sand_10x10x10_3d.options
echo "-ksp_rtol 1.0e-8 -ksp_atol 1.0e-8  -pc_type asm" > petsc.re_vgm_sand_10x10x10_3d.options
#echo "-log_trace -info -malloc -help" > petsc.options
ibrun parun re_vgm_sand_10x10x10_3d_p.py re_vgm_sand_10x10x10_3d_c0p1_n.py -l 3 -v -O petsc.re_vgm_sand_10x10x10_3d.options

