#PBS -A erdcvc2w
#PBS -l walltime=12:00:00
#PBS -l ncpus=32
#PBS -q challenge
#PBS -N adh.sloshbox3d
#PBS -j oe
env
which python
echo $PYTHONPATH
mkdir $WORKDIR/sloshbox3d.$PBS_JOBID
cd $PBS_O_WORKDIR
aprun -n 32 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_sloshbox_3d_old_so.py -l 3 -v -P "-ksp_type bcgsl -pc_type asm -pc_asm_type basic -sub_ksp_type preonly -sub_pc_type lu -sub_pc_factor_mat_solver_package spooles -ksp_rtol 0.0 -ksp_atol 1.0e-10 -ksp_monitor_true_residual"  -D $WORKDIR/sloshbox3d.$PBS_JOBID
cd $WORKDIR
tar czvf sloshbox3d.$PBS_JOBID.tar.gz sloshbox3d.$PBS_JOBID
mv -f sloshbox3d.$PBS_JOBID.tar.gz $HOME
