#PBS -A erdcvenq
#PBS -l walltime=00:30:00
#PBS -l ncpus=4
#PBS -q debug
#PBS -N adh.sloshbox3d
#PBS -j oe
mkdir $WORKDIR/sloshbox3d.$PBS_JOBID
cd $PBS_O_WORKDIR
aprun -a xt -n 4 parun twp_navier_stokes_sloshbox_3d_so.py -l 3 -v -P "-ksp_type bcgsl -pc_type asm -pc_asm_type basic -sub_ksp_type preonly -sub_pc_type lu -sub_pc_factor_mat_solver_packages superlu -ksp_rtol 0.0 -ksp_atol 1.0e-10"  -D $WORKDIR/sloshbox3d.$PBS_JOBID
