#PBS -A erdcvenq
#PBS -l walltime=48:00:00
#PBS -l ncpus=64
#PBS -q standard
#PBS -N adh.sloshbox2d
#PBS -j oe
mkdir $WORKDIR/sloshbox2d.$PBS_JOBID
cd $PBS_O_WORKDIR
aprun -n 64 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_sloshbox_2d_so.py -l 3 -v -P "-ksp_type bcgsl -pc_type asm -pc_asm_type basic -sub_ksp_type preonly -sub_pc_type lu -sub_pc_factor_mat_solver_package spooles -ksp_rtol 0.0 -ksp_atol 1.0e-10"  -D $WORKDIR/sloshbox2d.$PBS_JOBID
