#!/bin/tcsh 			  
#BSUB -J sloshbox3d
#BSUB -o oe.sloshbox3d.%J   
#BSUB -e oe.sloshbox3d.%J   
#BSUB -n 128 -W 48:00
#BSUB -q normal
set echo                          #Echo all commands.
cd $LS_SUBCWD                     #cd to directory of submissio
rm -f  petsc_options.sloshbox3d.txt
echo "-ksp_type bcgsl -pc_type asm -pc_asm_type_basic -ksp_rtol 0.0 -ksp_atol 1.0e-10 -ksp_monitor_true_residual -sub_ksp_type preonly -sub_pc_type lu -sub_pc_factor_mat_solver_package spooles" > petsc_options.sloshbox3d.txt
#echo "-ksp_type bcgsl -pc_type asm -pc_asm_type basic -ksp_rtol 0.0 -ksp_atol 1.0e-10  -sub_ksp_type preonly -sub_pc_type lu -ksp_monitor_true_residual" > petsc_options.sloshbox3d.txt
#echo "-ksp_type bcgsl -pc_type jacobi -ksp_rtol 0.0 -ksp_atol 1.0e-10  -ksp_monitor_true_residual" > petsc_options.sloshbox3d.txt
mkdir ${LSB_JOBNAME}.${LSB_JOBID}
ibrun python ../../scripts/parun twp_navier_stokes_sloshbox_3d_so.py -p -l 3 -v -O petsc_options.sloshbox3d.txt -D ${LSB_JOBNAME}.${LSB_JOBID}
tar cvf ${LSB_JOBNAME}.${LSB_JOBID}.tar ${LSB_JOBNAME}.${LSB_JOBID}
