#PBS -A erdcvc2w
#PBS -l walltime=12:00:00
#PBS -l ncpus=16
#PBS -q challenge
#PBS -N adh.threepcyl3d
#PBS -j oe
env
which python
echo $PYTHONPATH
mkdir $WORKDIR/threepcyl3d.$PBS_JOBID
cd $PBS_O_WORKDIR
aprun -n 16 python $PYADH/pyadhModule/scripts/parun threep_cylinder_md_3d_so.py -s -l 3 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/threepcyl3d.$PBS_JOBID
cd $WORKDIR
tar czvf threepcyl3d.$PBS_JOBID.tar.gz threepcyl3d.$PBS_JOBID
mv -f threepcyl3d.$PBS_JOBID.tar.gz $HOME
