#PBS -A erdcvc2w
#PBS -l walltime=16:00:00
#PBS -l ncpus=256
#PBS -q challenge
#PBS -N adh.wavetank2d
#PBS -j oe
env
which python
echo $PYTHONPATH
mkdir $WORKDIR/wavetank2d.$PBS_JOBID
cd $PBS_O_WORKDIR
#aprun -n 32 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_wavetank_2d_so.py -s -l 1 -v -P "-ksp_type gmres -pc_type asm -sub_pc_type lu -ksp_rtol 0.0 -ksp_atol 1.0e-8 -ksp_monitor"  -D $WORKDIR/wavetank2d.$PBS_JOBID
aprun -n 256 python $PYADH/pyadhModule/scripts/parun twp_navier_stokes_wavetank_2d_so.py -s -l 4 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package spooles"  -D $WORKDIR/wavetank2d.$PBS_JOBID
cd $WORKDIR
tar czvf wavetank2d.$PBS_JOBID.tar.gz wavetank2d.$PBS_JOBID
mv -f wavetank2d.$PBS_JOBID.tar.gz $HOME
#rm -rf wavetank2d.$PBS_JOBID
