#PBS -A erdcvenq
#PBS -l walltime=48:00:00
#PBS -l ncpus=128
#PBS -q standard
#PBS -N adh.wigley3d
#PBS -j oe
mkdir $WORKDIR/wigley3d.$PBS_JOBID
cd $PBS_O_WORKDIR
#aprun -n 128 python $PYADH/pyadhModule/scripts/parun wigley_so.py -l 3 -v -P "-ksp_type preonly -pc_type lu -pc_factor_mat_solver_package superlu_dist"  -D $WORKDIR/wigley3d.$PBS_JOBID
aprun -n 128 python $PYADH/pyadhModule/scripts/parun wigley_so.py -l 3 -v -P "-ksp_type bcgsl -pc_type asm -pc_asm_type basic -sub_ksp_type preonly -sub_pc_type lu -sub_pc_factor_mat_solver_package spooles -ksp_rtol 0.0 -ksp_atol 1.0e-10 -ksp_monitor_true_residual" -D $WORKDIR/wigley3d.$PBS_JOBID
