#ifndef MCORR3P_HPP
#define MCORR3P_HPP

#include <utility>
#include "xtensor-python/pyarray.hpp"

namespace proteus
{
    class cppMCorr3P_base
    {
    public:
        virtual ~cppMCorr3P_base() = default;

        virtual void calculateResidual(//element
                                       xt::pyarray<double> mesh_trial_ref,
                                       xt::pyarray<double> mesh_grad_trial_ref,
                                       xt::pyarray<double> mesh_dof,
                                       xt::pyarray<int> mesh_l2g,
                                       xt::pyarray<double> dV_ref,
                                       xt::pyarray<double> u_trial_ref,
                                       xt::pyarray<double> u_grad_trial_ref,
                                       xt::pyarray<double> u_test_ref,
                                       xt::pyarray<double> u_grad_test_ref,
                                       //element boundary
                                       xt::pyarray<double> mesh_trial_trace_ref,
                                       xt::pyarray<double> mesh_grad_trial_trace_ref,
                                       xt::pyarray<double> dS_ref,
                                       xt::pyarray<double> u_trial_trace_ref,
                                       xt::pyarray<double> u_grad_trial_trace_ref,
                                       xt::pyarray<double> u_test_trace_ref,
                                       xt::pyarray<double> u_grad_test_trace_ref,
                                       xt::pyarray<double> normal_ref,
                                       xt::pyarray<double> boundaryJac_ref,
                                       //physics
                                       int nElements_global,
                                       double useMetrics,
                                       double epsFactHeaviside,
                                       double epsFactDirac,
                                       double epsFactDiffusion,
                                       xt::pyarray<int> u_l2g,
                                       xt::pyarray<double> elementDiameter,
                                       xt::pyarray<double> nodeDiametersArray,
                                       xt::pyarray<double> u_dof,
                                       xt::pyarray<double> q_phi,
                                       xt::pyarray<double> q_normal_phi,
                                       xt::pyarray<double> ebqe_phi,
                                       xt::pyarray<double> ebqe_normal_phi,
                                       xt::pyarray<double> q_H,
                                       xt::pyarray<double> q_u,
                                       xt::pyarray<double> q_n,
                                       xt::pyarray<double> ebqe_u,
                                       xt::pyarray<double> ebqe_n,
                                       xt::pyarray<double> q_r,
                                       xt::pyarray<double> q_vos,
                                       int offset_u, int stride_u,
                                       xt::pyarray<double> globalResidual,
                                       int nExteriorElementBoundaries_global,
                                       xt::pyarray<int> exteriorElementBoundariesArray,
                                       xt::pyarray<int> elementBoundaryElementsArray,
                                       xt::pyarray<int> elementBoundaryLocalElementBoundariesArray,
				       // fast (jacobian) assembly
				       xt::pyarray<double> interface_lumpedMassMatrix) = 0;
  
        virtual void calculateJacobian(//element
                                       xt::pyarray<double> mesh_trial_ref,
                                       xt::pyarray<double> mesh_grad_trial_ref,
                                       xt::pyarray<double> mesh_dof,
                                       xt::pyarray<int> mesh_l2g,
                                       xt::pyarray<double> dV_ref,
                                       xt::pyarray<double> u_trial_ref,
                                       xt::pyarray<double> u_grad_trial_ref,
                                       xt::pyarray<double> u_test_ref,
                                       xt::pyarray<double> u_grad_test_ref,
                                       //element boundary
                                       xt::pyarray<double> mesh_trial_trace_ref,
                                       xt::pyarray<double> mesh_grad_trial_trace_ref,
                                       xt::pyarray<double> dS_ref,
                                       xt::pyarray<double> u_trial_trace_ref,
                                       xt::pyarray<double> u_grad_trial_trace_ref,
                                       xt::pyarray<double> u_test_trace_ref,
                                       xt::pyarray<double> u_grad_test_trace_ref,
                                       xt::pyarray<double> normal_ref,
                                       xt::pyarray<double> boundaryJac_ref,
                                       //physics
                                       int nElements_global,
                                       double useMetrics,
                                       double epsFactHeaviside,
                                       double epsFactDirac,
                                       double epsFactDiffusion,
                                       xt::pyarray<int> u_l2g,
                                       xt::pyarray<double> elementDiameter,
                                       xt::pyarray<double> nodeDiametersArray,
                                       xt::pyarray<double> u_dof,
                                       xt::pyarray<double> q_phi,
                                       xt::pyarray<double> q_normal_phi,
                                       xt::pyarray<double> q_H,
                                       xt::pyarray<double> q_vos,
                                       xt::pyarray<int> csrRowIndeces_u_u,xt::pyarray<int> csrColumnOffsets_u_u,
                                       xt::pyarray<double> globalJacobian,
				       // Fast assembly
				       int numDOFs,
				       xt::pyarray<int> csrRowIndeces_DofLoops,
				       xt::pyarray<int> csrColumnOffsets_DofLoops,
				       xt::pyarray<double> stiffness_matrix,
				       xt::pyarray<double> interface_lumpedMassMatrix) = 0;
  
        virtual void elementSolve(//element
                                   xt::pyarray<double> mesh_trial_ref,
                                   xt::pyarray<double> mesh_grad_trial_ref,
                                   xt::pyarray<double> mesh_dof,
                                   xt::pyarray<int> mesh_l2g,
                                   xt::pyarray<double> dV_ref,
                                   xt::pyarray<double> u_trial_ref,
                                   xt::pyarray<double> u_grad_trial_ref,
                                   xt::pyarray<double> u_test_ref,
                                   xt::pyarray<double> u_grad_test_ref,
                                   //element boundary
                                   xt::pyarray<double> mesh_trial_trace_ref,
                                   xt::pyarray<double> mesh_grad_trial_trace_ref,
                                   xt::pyarray<double> dS_ref,
                                   xt::pyarray<double> u_trial_trace_ref,
                                   xt::pyarray<double> u_grad_trial_trace_ref,
                                   xt::pyarray<double> u_test_trace_ref,
                                   xt::pyarray<double> u_grad_test_trace_ref,
                                   xt::pyarray<double> normal_ref,
                                   xt::pyarray<double> boundaryJac_ref,
                                   //physics
                                   int nElements_global,
                                   double useMetrics,
                                   double epsFactHeaviside,
                                   double epsFactDirac,
                                   double epsFactDiffusion,
                                   xt::pyarray<int> u_l2g,
                                   xt::pyarray<double> elementDiameter,
                                   xt::pyarray<double> nodeDiametersArray,
                                   xt::pyarray<double> u_dof,
                                   xt::pyarray<double> q_phi,
                                   xt::pyarray<double> q_normal_phi,
                                   xt::pyarray<double> ebqe_phi,
                                   xt::pyarray<double> ebqe_normal_phi,
                                   xt::pyarray<double> q_H,
                                   xt::pyarray<double> q_u,
                                   xt::pyarray<double> q_n,
                                   xt::pyarray<double> ebqe_u,
                                   xt::pyarray<double> ebqe_n,
                                   xt::pyarray<double> q_r,
                                   xt::pyarray<double> q_vos,
                                   int offset_u, int stride_u,
                                   xt::pyarray<double> globalResidual,
                                   int nExteriorElementBoundaries_global,
                                   xt::pyarray<int> exteriorElementBoundariesArray,
                                   xt::pyarray<int> elementBoundaryElementsArray,
                                   xt::pyarray<int> elementBoundaryLocalElementBoundariesArray,
                                   int maxIts,
                                   double atol) = 0;

        virtual void elementConstantSolve(//element
                                   xt::pyarray<double> mesh_trial_ref,
                                   xt::pyarray<double> mesh_grad_trial_ref,
                                   xt::pyarray<double> mesh_dof,
                                   xt::pyarray<int> mesh_l2g,
                                   xt::pyarray<double> dV_ref,
                                   xt::pyarray<double> u_trial_ref,
                                   xt::pyarray<double> u_grad_trial_ref,
                                   xt::pyarray<double> u_test_ref,
                                   xt::pyarray<double> u_grad_test_ref,
                                   //element boundary
                                   xt::pyarray<double> mesh_trial_trace_ref,
                                   xt::pyarray<double> mesh_grad_trial_trace_ref,
                                   xt::pyarray<double> dS_ref,
                                   xt::pyarray<double> u_trial_trace_ref,
                                   xt::pyarray<double> u_grad_trial_trace_ref,
                                   xt::pyarray<double> u_test_trace_ref,
                                   xt::pyarray<double> u_grad_test_trace_ref,
                                   xt::pyarray<double> normal_ref,
                                   xt::pyarray<double> boundaryJac_ref,
                                   //physics
                                   int nElements_global,
                                   double useMetrics,
                                   double epsFactHeaviside,
                                   double epsFactDirac,
                                   double epsFactDiffusion,
                                   xt::pyarray<int> u_l2g,
                                   xt::pyarray<double> elementDiameter,
                                   xt::pyarray<double> nodeDiametersArray,
                                   xt::pyarray<double> u_dof,
                                   xt::pyarray<double> q_phi,
                                   xt::pyarray<double> q_normal_phi,
                                   xt::pyarray<double> ebqe_phi,
                                   xt::pyarray<double> ebqe_normal_phi,
                                   xt::pyarray<double> q_H,
                                   xt::pyarray<double> q_u,
                                   xt::pyarray<double> q_n,
                                   xt::pyarray<double> ebqe_u,
                                   xt::pyarray<double> ebqe_n,
                                   xt::pyarray<double> q_r,
                                   xt::pyarray<double> q_vos,
                                   int offset_u, int stride_u,
                                   xt::pyarray<double> globalResidual,
                                   int nExteriorElementBoundaries_global,
                                   xt::pyarray<int> exteriorElementBoundariesArray,
                                   xt::pyarray<int> elementBoundaryElementsArray,
                                   xt::pyarray<int> elementBoundaryLocalElementBoundariesArray,
                                   int maxIts,
                                   double atol) = 0;
        
        virtual std::pair<double, double> globalConstantRJ(//element
                                                           xt::pyarray<double> mesh_trial_ref,
                                                           xt::pyarray<double> mesh_grad_trial_ref,
                                                           xt::pyarray<double> mesh_dof,
                                                           xt::pyarray<int> mesh_l2g,
                                                           xt::pyarray<double> dV_ref,
                                                           xt::pyarray<double> u_trial_ref,
                                                           xt::pyarray<double> u_grad_trial_ref,
                                                           xt::pyarray<double> u_test_ref,
                                                           xt::pyarray<double> u_grad_test_ref,
                                                           //element boundary
                                                           xt::pyarray<double> mesh_trial_trace_ref,
                                                           xt::pyarray<double> mesh_grad_trial_trace_ref,
                                                           xt::pyarray<double> dS_ref,
                                                           xt::pyarray<double> u_trial_trace_ref,
                                                           xt::pyarray<double> u_grad_trial_trace_ref,
                                                           xt::pyarray<double> u_test_trace_ref,
                                                           xt::pyarray<double> u_grad_test_trace_ref,
                                                           xt::pyarray<double> normal_ref,
                                                           xt::pyarray<double> boundaryJac_ref,
                                                           //physics
                                                           int nElements_owned,
                                                           double useMetrics,
                                                           double epsFactHeaviside,
                                                           double epsFactDirac,
                                                           double epsFactDiffusion,
                                                           xt::pyarray<int> u_l2g,
                                                           xt::pyarray<double> elementDiameter,
                                                           xt::pyarray<double> nodeDiametersArray,
                                                           xt::pyarray<double> u_dof,
                                                           xt::pyarray<double> q_phi,
                                                           xt::pyarray<double> q_normal_phi,
                                                           xt::pyarray<double> ebqe_phi,
                                                           xt::pyarray<double> ebqe_normal_phi,
                                                           xt::pyarray<double> q_H,
                                                           xt::pyarray<double> q_u,
                                                           xt::pyarray<double> q_n,
                                                           xt::pyarray<double> ebqe_u,
                                                           xt::pyarray<double> ebqe_n,
                                                           xt::pyarray<double> q_r,
                                                           xt::pyarray<double> q_vos,
                                                           int offset_u, int stride_u,
                                                           xt::pyarray<double> globalResidual,
                                                           int nExteriorElementBoundaries_global,
                                                           xt::pyarray<int> exteriorElementBoundariesArray,
                                                           xt::pyarray<int> elementBoundaryElementsArray,
                                                           xt::pyarray<int> elementBoundaryLocalElementBoundariesArray,
                                                           int maxIts,
                                                           double atol,
                                                           double constant_u) = 0;

        virtual double calculateMass(//element
                                     xt::pyarray<double> mesh_trial_ref,
                                     xt::pyarray<double> mesh_grad_trial_ref,
                                     xt::pyarray<double> mesh_dof,
                                     xt::pyarray<int> mesh_l2g,
                                     xt::pyarray<double> dV_ref,
                                     xt::pyarray<double> u_trial_ref,
                                     xt::pyarray<double> u_grad_trial_ref,
                                     xt::pyarray<double> u_test_ref,
                                     xt::pyarray<double> u_grad_test_ref,
                                     //element boundary
                                     xt::pyarray<double> mesh_trial_trace_ref,
                                     xt::pyarray<double> mesh_grad_trial_trace_ref,
                                     xt::pyarray<double> dS_ref,
                                     xt::pyarray<double> u_trial_trace_ref,
                                     xt::pyarray<double> u_grad_trial_trace_ref,
                                     xt::pyarray<double> u_test_trace_ref,
                                     xt::pyarray<double> u_grad_test_trace_ref,
                                     xt::pyarray<double> normal_ref,
                                     xt::pyarray<double> boundaryJac_ref,
                                     //physics
                                     int nElements_owned,
                                     double useMetrics,
                                     double epsFactHeaviside,
                                     double epsFactDirac,
                                     double epsFactDiffusion,
                                     xt::pyarray<int> u_l2g,
                                     xt::pyarray<double> elementDiameter,
                                     xt::pyarray<double> nodeDiametersArray,
                                     xt::pyarray<double> u_dof,
                                     xt::pyarray<double> q_phi,
                                     xt::pyarray<double> q_normal_phi,
                                     xt::pyarray<double> ebqe_phi,
                                     xt::pyarray<double> ebqe_normal_phi,
                                     xt::pyarray<double> q_H,
                                     xt::pyarray<double> q_u,
                                     xt::pyarray<double> q_n,
                                     xt::pyarray<double> ebqe_u,
                                     xt::pyarray<double> ebqe_n,
                                     xt::pyarray<double> q_r,
                                     xt::pyarray<double> q_vos,
                                     int offset_u, int stride_u,
                                     xt::pyarray<double> globalResidual,
                                     int nExteriorElementBoundaries_global,
                                     xt::pyarray<int> exteriorElementBoundariesArray,
                                     xt::pyarray<int> elementBoundaryElementsArray,
                                     xt::pyarray<int> elementBoundaryLocalElementBoundariesArray) = 0;

        virtual void setMassQuadrature(//element
                                       xt::pyarray<double> mesh_trial_ip,
                                       xt::pyarray<double> mesh_trial_ref,
                                       xt::pyarray<double> mesh_grad_trial_ref,
                                       xt::pyarray<double> mesh_dof,
                                       xt::pyarray<int> mesh_l2g,
                                       xt::pyarray<double> dV_ref,
                                       xt::pyarray<double> u_trial_ref,
                                       xt::pyarray<double> u_grad_trial_ref,
                                       xt::pyarray<double> u_test_ref,
                                       xt::pyarray<double> u_grad_test_ref,
                                       //element boundary
                                       xt::pyarray<double> mesh_trial_trace_ref,
                                       xt::pyarray<double> mesh_grad_trial_trace_ref,
                                       xt::pyarray<double> dS_ref,
                                       xt::pyarray<double> u_trial_trace_ref,
                                       xt::pyarray<double> u_grad_trial_trace_ref,
                                       xt::pyarray<double> u_test_trace_ref,
                                       xt::pyarray<double> u_grad_test_trace_ref,
                                       xt::pyarray<double> normal_ref,
                                       xt::pyarray<double> boundaryJac_ref,
                                       //physics
                                       int nElements_global,
                                       double useMetrics,
                                       double epsFactHeaviside,
                                       double epsFactDirac,
                                       double epsFactDiffusion,
                                       xt::pyarray<int> phi_l2g,
                                       xt::pyarray<double> elementDiameter,
                                       xt::pyarray<double> nodeDiametersArray,
                                       xt::pyarray<double> phi_dof,
                                       xt::pyarray<double> q_phi,
                                       xt::pyarray<double> q_normal_phi,
                                       xt::pyarray<double> ebqe_phi,
                                       xt::pyarray<double> ebqe_normal_phi,
                                       xt::pyarray<double> q_H,
                                       xt::pyarray<double> q_u,
                                       xt::pyarray<double> q_n,
                                       xt::pyarray<double> ebqe_u,
                                       xt::pyarray<double> ebqe_n,
                                       xt::pyarray<double> q_r,
                                       xt::pyarray<double> q_vos,
                                       int offset_u, int stride_u,
                                       xt::pyarray<double> globalResidual,
                                       int nExteriorElementBoundaries_global,
                                       xt::pyarray<int> exteriorElementBoundariesArray,
                                       xt::pyarray<int> elementBoundaryElementsArray,
                                       xt::pyarray<int> elementBoundaryLocalElementBoundariesArray,
                                       xt::pyarray<double> H_dof) = 0;

        virtual void calculateStiffnessMatrix(//element
					      xt::pyarray<double> mesh_trial_ref,
					      xt::pyarray<double> mesh_grad_trial_ref,
					      xt::pyarray<double> mesh_dof,
					      xt::pyarray<int> mesh_l2g,
					      xt::pyarray<double> dV_ref,
					      xt::pyarray<double> u_grad_trial_ref,
					      int nElements_global,
					      xt::pyarray<int> csrRowIndeces_u_u,xt::pyarray<int> csrColumnOffsets_u_u,
					      xt::pyarray<double> globalJacobian,
					      double useMetrics,
					      double epsFactDiffusion,
					      xt::pyarray<double> elementDiameter,
					      xt::pyarray<double> nodeDiametersArray) = 0;
    };

    cppMCorr3P_base* newMCorr3P(int nSpaceIn,
                                int nQuadraturePoints_elementIn,
                                int nDOF_mesh_trial_elementIn,
                                int nDOF_trial_elementIn,
                                int nDOF_test_elementIn,
                                int nQuadraturePoints_elementBoundaryIn,
                                int CompKernelFlag);

}

#endif

