"""
Modules for computing numerical solutions of differential equations
"""

__version__ = '0.9.0'

__all__ = ["Archiver",
           "Domain",
           "InputTranslators",
           "SplitOperator",
           "StepControl",
           "NumericalSolution",
           "Comm",
           "AnalyticalSolutions",
           "TransportCoefficients",
           "TwophaseDarcyCoefficients",
           "DiagUtils",
           "EGeometry",
           "ErrorEstimators",
           "FemTools",
           "LatexReport",
           "LinearAlgebraTools",
           "LinearSolvers",
           "MeshTools",
           "NonlinearSolvers",
           "Norms",
           "NumericalFlux",
           "PostProcessingTools",
           "Profiling",
           "Quadrature",
           "RefUtils",
           "ShockCapturing",
           "SimTools",
           "SubgridError",
           "SubsurfaceTransportCoefficients",
           "StupidHeap",
           "TimeIntegration",
#           "Tracking",
           "Transport",
           "TriangleTools",
           "UnstructuredFMMandFSWsolvers",
           "Viewers",
           "AuxiliaryVariables",
           "default_p",
           "default_n",
           "default_s",
           "default_so",
           "InputTranslators",
           "cfemIntegrals",
           "cshockCapturing",
           "csmoothers",
           "csubgridError",
           "ctimeIntegration",
           "ctransportCoefficients",
           "lapackWrappers",
           "superluWrappers",
           "triangleWrappers",
           "testStuff",
           "testStuffImpl",
           "cmeshTools",
           "cnumericalFlux",
           "cfmmfsw",
           "cTwophaseDarcyCoefficients"]
