#PBS -A ERDCV00898ENQ
#PBS -l walltime=001:00:00
#PBS -l ncpus=32
#PBS -q debug
#PBS -N testProteus
#PBS -j oe
#PBS -l application=proteus
#PBS -l ccm=1
cd $PBS_O_WORKDIR
echo "testing import"
echo "testing poisson 1 way on 1 nodes"
aprun -n 1 ${PROTEUS_PYTHON} test_import.py
echo "testing poisson 2 way on 1 nodes"
aprun -n 2 -N 2 ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 4 way on 1 nodes"
aprun -n 4 -N 4 -S 1 ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 8 way on 1 nodes"
aprun -n 8 -N 8 -S 2 ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 16 way on 1 nodes"
aprun -n 16 -N 16 -S 4 ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 1 way on 2 nodes"
aprun -n 2 -N 1  ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 4 way on 2 nodes"
aprun -n 8 -N 4  -S 1  ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 8 way on 2 nodes"
aprun -n 16 -N 8  -S 2  ${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 16 way on 2 nodes"
aprun -n 32 -N 16  -S 4  ${PROTEUS_PYTHON} test_poisson.py
