#PBS -A ERDCV00898ENQ
#PBS -l walltime=00:60:00
#PBS -l ncpus=128
#PBS -q debug
#PBS -N testProteus
#PBS -j oe
#PBS -l application=proteus
cd $PBS_O_WORKDIR
cd ${PROTEUS}/externalPackages/petsc4py/test
echo "testing import"
aprun -n 1 ${PROTEUS_PYTHON} test_import.py
echo "testing poisson 1 way on 8 nodes"
aprun -n 8 -N 1 -${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 8 way on 1 node"
aprun -n 8 -N 8 -${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 16 way on 1 node"
aprun -n 16 -N 16 -${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 8 way on 8 nodes"
aprun -n 64 -N 8 -${PROTEUS_PYTHON} test_poisson.py
echo "testing poisson 16 way on 8 nodes"
aprun -n 128 -N 16 -${PROTEUS_PYTHON} test_poisson.py
