#! /bin/bash
#PBS -A ERDCV00898ENQ
#PBS -l walltime=001:00:00
#PBS -N testProteus
#PBS -q debug
#PBS -j oe
#PBS -l select=1:ncpus=8:mpiprocs=1
#PBS -l place=scatter:excl
#PBS -l application=proteus
cd ${PROTEUS}/proteusModule/test
echo "starting proteus tests"
#${HOME}/BOB/mpirun -np 1 ${PROTEUS_PYTHON} -c "import nose; nose.test()"
#mpirun -np 1 parun poisson_3d_p.py poisson_3d_c0p1_n.py -l 5 -v
#${HOME}/BOB/mpirun -np 1 ${PROTEUS_PYTHON} test_import.py
#${HOME}/BOB/mpirun -np 1 ${PROTEUS_PYTHON} test_poisson.py
#${HOME}/BOB/mpirun -np 8 ${PROTEUS_PYTHON} test_poisson.py
mpirun -np 1 ${PROTEUS_PYTHON} -c "print hello"
