./config/configure.py --prefix=${PROTEUS_PREFIX} \
--with-pic \
--with-clanguage=C \
--with-mpi-compilers=1 \
--with-cc="cc" \
--with-cxx="CC" \
--with-fc="ftn" \
--with-shared-libraries \
--with-blas-lapack-lib=\[/opt/acml/4.4.0/gnu64/lib/libacml.so\] \
--download-parmetis=1 \
--download-blacs=1 \
--download-scalapack=1 \
--download-mumps=1 \
--download-superlu=1 \
--download-superlu_dist=1 \
--download-hypre=1
