/* File: ftrackingmodule.c
 * This file is auto-generated with f2py (version:2_5972).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Mar 26 11:07:01 2010
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *ftracking_error;
static PyObject *ftracking_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    PyErr_SetString(ftracking_error,"("tcheck") failed for "name);\
    fprintf(stderr,show"\n",var);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = ftracking_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = ftracking_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(foo,FOO)(int*,int*,int*,double*,int*);
extern void F_FUNC(foo2,FOO2)(int*,int*,double*);
extern void F_FUNC(sspt123,SSPT123)(int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,int*,int*,int*,double*,double*,double*,double*,int*,int*,double*);
extern void F_FUNC(eltrak123,ELTRAK123)(int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,double*,double*,int*,int*,int*);
extern void F_FUNC_US(dn_check,DN_CHECK)(int*,int*,int*,double*,double*,double*,int*,int*,int*);
extern void F_FUNC_US(rkck_pt,RKCK_PT)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC(vel123,VEL123)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC(intrp123,INTRP123)(int*,int*,int*,int*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ foo ************************************/
static char doc_f2py_rout_ftracking_foo[] = "\
Function signature:\n\
  foo(a,b,[nd,n,m])\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (nd)\n"
"  b : input rank-2 array('i') with bounds (n,m)\n"
"Optional arguments:\n"
"  nd := len(a) input int\n"
"  n := shape(b,0) input int\n"
"  m := shape(b,1) input int";
/* extern void F_FUNC(foo,FOO)(int*,int*,int*,double*,int*); */
static PyObject *f2py_rout_ftracking_foo(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nd = 0;
  PyObject *nd_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","nd","n","m",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OOO:ftracking.foo",\
    capi_kwlist,&a_capi,&b_capi,&nd_capi,&n_capi,&m_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 1st argument `a' of ftracking.foo to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(PyArray_INT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 2nd argument `b' of ftracking.foo to C/Fortran array" );
  } else {
    b = (int *)(capi_b_tmp->data);

  /* Processing variable m */
  if (m_capi == Py_None) m = shape(b,1); else
    f2py_success = int_from_pyobj(&m,m_capi,"ftracking.foo() 3rd keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,1)==m,"shape(b,1)==m","3rd keyword m","foo:m=%d",m) {
  /* Processing variable nd */
  if (nd_capi == Py_None) nd = len(a); else
    f2py_success = int_from_pyobj(&nd,nd_capi,"ftracking.foo() 1st keyword (nd) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(a)>=nd,"len(a)>=nd","1st keyword nd","foo:nd=%d",nd) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(b,0); else
    f2py_success = int_from_pyobj(&n,n_capi,"ftracking.foo() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==n,"shape(b,0)==n","2nd keyword n","foo:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nd,&n,&m,a,b);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(b,0)==n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(len(a)>=nd)*/
  } /*if (f2py_success) of nd*/
  /* End of cleaning variable nd */
  } /*CHECKSCALAR(shape(b,1)==m)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of foo *********************************/

/************************************ foo2 ************************************/
static char doc_f2py_rout_ftracking_foo2[] = "\
Function signature:\n\
  foo2(xg,[neq,nnp])\n\
Required arguments:\n"
"  xg : input rank-2 array('d') with bounds (neq,nnp)\n"
"Optional arguments:\n"
"  neq := shape(xg,0) input int\n"
"  nnp := shape(xg,1) input int";
/* extern void F_FUNC(foo2,FOO2)(int*,int*,double*); */
static PyObject *f2py_rout_ftracking_foo2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int neq = 0;
  PyObject *neq_capi = Py_None;
  int nnp = 0;
  PyObject *nnp_capi = Py_None;
  double *xg = NULL;
  npy_intp xg_Dims[2] = {-1, -1};
  const int xg_Rank = 2;
  PyArrayObject *capi_xg_tmp = NULL;
  int capi_xg_intent = 0;
  PyObject *xg_capi = Py_None;
  static char *capi_kwlist[] = {"xg","neq","nnp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|OO:ftracking.foo2",\
    capi_kwlist,&xg_capi,&neq_capi,&nnp_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xg */
  ;
  capi_xg_intent |= F2PY_INTENT_IN;
  capi_xg_tmp = array_from_pyobj(PyArray_DOUBLE,xg_Dims,xg_Rank,capi_xg_intent,xg_capi);
  if (capi_xg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 1st argument `xg' of ftracking.foo2 to C/Fortran array" );
  } else {
    xg = (double *)(capi_xg_tmp->data);

  /* Processing variable nnp */
  if (nnp_capi == Py_None) nnp = shape(xg,1); else
    f2py_success = int_from_pyobj(&nnp,nnp_capi,"ftracking.foo2() 2nd keyword (nnp) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xg,1)==nnp,"shape(xg,1)==nnp","2nd keyword nnp","foo2:nnp=%d",nnp) {
  /* Processing variable neq */
  if (neq_capi == Py_None) neq = shape(xg,0); else
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.foo2() 1st keyword (neq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xg,0)==neq,"shape(xg,0)==neq","1st keyword neq","foo2:neq=%d",neq) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&neq,&nnp,xg);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(xg,0)==neq)*/
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  } /*CHECKSCALAR(shape(xg,1)==nnp)*/
  } /*if (f2py_success) of nnp*/
  /* End of cleaning variable nnp */
  if((PyObject *)capi_xg_tmp!=xg_capi) {
    Py_XDECREF(capi_xg_tmp); }
  }  /*if (capi_xg_tmp == NULL) ... else of xg*/
  /* End of cleaning variable xg */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of foo2 ********************************/

/********************************** sspt123 **********************************/
static char doc_f2py_rout_ftracking_sspt123[] = "\
Function signature:\n\
  sspt123(nnp,nel,nnde,neq,npt,ibf,lu_o,atol,rtol,sf,dn_safe,xg,ie,nlrl,lrl,vtl2g,vt1e,x_i,t_i,tpt,mpt,idpt,xpt,[maxeq])\n\
Required arguments:\n"
"  nnp : input int\n"
"  nel : input int\n"
"  nnde : input int\n"
"  neq : input int\n"
"  npt := len(t_i) input int\n"
"  ibf : input int\n"
"  lu_o : input int\n"
"  atol : input float\n"
"  rtol : input float\n"
"  sf : input float\n"
"  dn_safe : input float\n"
"  xg : input rank-1 array('d') with bounds (maxeq*nnp)\n"
"  ie : input rank-1 array('i') with bounds (nnde*nel)\n"
"  nlrl : input rank-1 array('i') with bounds (*)\n"
"  lrl : input rank-1 array('i') with bounds (*)\n"
"  vtl2g : input rank-1 array('i') with bounds (neq*nnde*nel)\n"
"  vt1e : input rank-1 array('d') with bounds (*)\n"
"  x_i : input rank-1 array('d') with bounds (maxeq*npt)\n"
"  t_i : input rank-1 array('d') with bounds (npt)\n"
"  tpt :  rank-1 array('d') with bounds (npt)\n"
"  mpt :  rank-1 array('i') with bounds (npt)\n"
"  idpt :  rank-1 array('i') with bounds (npt)\n"
"  xpt :  rank-1 array('d') with bounds (maxeq*npt)\n"
"Optional arguments:\n"
"  maxeq := 3 input int";
/* extern void F_FUNC(sspt123,SSPT123)(int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,int*,int*,int*,double*,double*,double*,double*,int*,int*,double*); */
static PyObject *f2py_rout_ftracking_sspt123(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,int*,int*,int*,double*,double*,double*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int maxeq = 0;
  PyObject *maxeq_capi = Py_None;
  int nnp = 0;
  PyObject *nnp_capi = Py_None;
  int nel = 0;
  PyObject *nel_capi = Py_None;
  int nnde = 0;
  PyObject *nnde_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  int npt = 0;
  PyObject *npt_capi = Py_None;
  int ibf = 0;
  PyObject *ibf_capi = Py_None;
  int lu_o = 0;
  PyObject *lu_o_capi = Py_None;
  double atol = 0;
  PyObject *atol_capi = Py_None;
  double rtol = 0;
  PyObject *rtol_capi = Py_None;
  double sf = 0;
  PyObject *sf_capi = Py_None;
  double dn_safe = 0;
  PyObject *dn_safe_capi = Py_None;
  double *xg = NULL;
  npy_intp xg_Dims[1] = {-1};
  const int xg_Rank = 1;
  PyArrayObject *capi_xg_tmp = NULL;
  int capi_xg_intent = 0;
  PyObject *xg_capi = Py_None;
  int *ie = NULL;
  npy_intp ie_Dims[1] = {-1};
  const int ie_Rank = 1;
  PyArrayObject *capi_ie_tmp = NULL;
  int capi_ie_intent = 0;
  PyObject *ie_capi = Py_None;
  int *nlrl = NULL;
  npy_intp nlrl_Dims[1] = {-1};
  const int nlrl_Rank = 1;
  PyArrayObject *capi_nlrl_tmp = NULL;
  int capi_nlrl_intent = 0;
  PyObject *nlrl_capi = Py_None;
  int *lrl = NULL;
  npy_intp lrl_Dims[1] = {-1};
  const int lrl_Rank = 1;
  PyArrayObject *capi_lrl_tmp = NULL;
  int capi_lrl_intent = 0;
  PyObject *lrl_capi = Py_None;
  int *vtl2g = NULL;
  npy_intp vtl2g_Dims[1] = {-1};
  const int vtl2g_Rank = 1;
  PyArrayObject *capi_vtl2g_tmp = NULL;
  int capi_vtl2g_intent = 0;
  PyObject *vtl2g_capi = Py_None;
  double *vt1e = NULL;
  npy_intp vt1e_Dims[1] = {-1};
  const int vt1e_Rank = 1;
  PyArrayObject *capi_vt1e_tmp = NULL;
  int capi_vt1e_intent = 0;
  PyObject *vt1e_capi = Py_None;
  double *x_i = NULL;
  npy_intp x_i_Dims[1] = {-1};
  const int x_i_Rank = 1;
  PyArrayObject *capi_x_i_tmp = NULL;
  int capi_x_i_intent = 0;
  PyObject *x_i_capi = Py_None;
  double *t_i = NULL;
  npy_intp t_i_Dims[1] = {-1};
  const int t_i_Rank = 1;
  PyArrayObject *capi_t_i_tmp = NULL;
  int capi_t_i_intent = 0;
  PyObject *t_i_capi = Py_None;
  double *tpt = NULL;
  npy_intp tpt_Dims[1] = {-1};
  const int tpt_Rank = 1;
  PyArrayObject *capi_tpt_tmp = NULL;
  int capi_tpt_intent = 0;
  PyObject *tpt_capi = Py_None;
  int *mpt = NULL;
  npy_intp mpt_Dims[1] = {-1};
  const int mpt_Rank = 1;
  PyArrayObject *capi_mpt_tmp = NULL;
  int capi_mpt_intent = 0;
  PyObject *mpt_capi = Py_None;
  int *idpt = NULL;
  npy_intp idpt_Dims[1] = {-1};
  const int idpt_Rank = 1;
  PyArrayObject *capi_idpt_tmp = NULL;
  int capi_idpt_intent = 0;
  PyObject *idpt_capi = Py_None;
  double *xpt = NULL;
  npy_intp xpt_Dims[1] = {-1};
  const int xpt_Rank = 1;
  PyArrayObject *capi_xpt_tmp = NULL;
  int capi_xpt_intent = 0;
  PyObject *xpt_capi = Py_None;
  static char *capi_kwlist[] = {"nnp","nel","nnde","neq","npt","ibf","lu_o","atol","rtol","sf","dn_safe","xg","ie","nlrl","lrl","vtl2g","vt1e","x_i","t_i","tpt","mpt","idpt","xpt","maxeq",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOO|O:ftracking.sspt123",\
    capi_kwlist,&nnp_capi,&nel_capi,&nnde_capi,&neq_capi,&npt_capi,&ibf_capi,&lu_o_capi,&atol_capi,&rtol_capi,&sf_capi,&dn_safe_capi,&xg_capi,&ie_capi,&nlrl_capi,&lrl_capi,&vtl2g_capi,&vt1e_capi,&x_i_capi,&t_i_capi,&tpt_capi,&mpt_capi,&idpt_capi,&xpt_capi,&maxeq_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dn_safe */
    f2py_success = double_from_pyobj(&dn_safe,dn_safe_capi,"ftracking.sspt123() 11st argument (dn_safe) can't be converted to double");
  if (f2py_success) {
  /* Processing variable rtol */
    f2py_success = double_from_pyobj(&rtol,rtol_capi,"ftracking.sspt123() 9th argument (rtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lrl */
  ;
  capi_lrl_intent |= F2PY_INTENT_IN;
  capi_lrl_tmp = array_from_pyobj(PyArray_INT,lrl_Dims,lrl_Rank,capi_lrl_intent,lrl_capi);
  if (capi_lrl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 15th argument `lrl' of ftracking.sspt123 to C/Fortran array" );
  } else {
    lrl = (int *)(capi_lrl_tmp->data);

  /* Processing variable atol */
    f2py_success = double_from_pyobj(&atol,atol_capi,"ftracking.sspt123() 8th argument (atol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nlrl */
  ;
  capi_nlrl_intent |= F2PY_INTENT_IN;
  capi_nlrl_tmp = array_from_pyobj(PyArray_INT,nlrl_Dims,nlrl_Rank,capi_nlrl_intent,nlrl_capi);
  if (capi_nlrl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 14th argument `nlrl' of ftracking.sspt123 to C/Fortran array" );
  } else {
    nlrl = (int *)(capi_nlrl_tmp->data);

  /* Processing variable ibf */
    f2py_success = int_from_pyobj(&ibf,ibf_capi,"ftracking.sspt123() 6th argument (ibf) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxeq */
  if (maxeq_capi == Py_None) maxeq = 3; else
    f2py_success = int_from_pyobj(&maxeq,maxeq_capi,"ftracking.sspt123() 1st keyword (maxeq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nnp */
    f2py_success = int_from_pyobj(&nnp,nnp_capi,"ftracking.sspt123() 1st argument (nnp) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nel */
    f2py_success = int_from_pyobj(&nel,nel_capi,"ftracking.sspt123() 2nd argument (nel) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t_i */
  ;
  capi_t_i_intent |= F2PY_INTENT_IN;
  capi_t_i_tmp = array_from_pyobj(PyArray_DOUBLE,t_i_Dims,t_i_Rank,capi_t_i_intent,t_i_capi);
  if (capi_t_i_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 19th argument `t_i' of ftracking.sspt123 to C/Fortran array" );
  } else {
    t_i = (double *)(capi_t_i_tmp->data);

  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.sspt123() 4th argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lu_o */
    f2py_success = int_from_pyobj(&lu_o,lu_o_capi,"ftracking.sspt123() 7th argument (lu_o) can't be converted to int");
  if (f2py_success) {
  /* Processing variable vt1e */
  ;
  capi_vt1e_intent |= F2PY_INTENT_IN;
  capi_vt1e_tmp = array_from_pyobj(PyArray_DOUBLE,vt1e_Dims,vt1e_Rank,capi_vt1e_intent,vt1e_capi);
  if (capi_vt1e_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 17th argument `vt1e' of ftracking.sspt123 to C/Fortran array" );
  } else {
    vt1e = (double *)(capi_vt1e_tmp->data);

  /* Processing variable nnde */
    f2py_success = int_from_pyobj(&nnde,nnde_capi,"ftracking.sspt123() 3rd argument (nnde) can't be converted to int");
  if (f2py_success) {
  /* Processing variable sf */
    f2py_success = double_from_pyobj(&sf,sf_capi,"ftracking.sspt123() 10th argument (sf) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xg */
  xg_Dims[0]=maxeq*nnp;
  capi_xg_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_xg_tmp = array_from_pyobj(PyArray_DOUBLE,xg_Dims,xg_Rank,capi_xg_intent,xg_capi);
  if (capi_xg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 12nd argument `xg' of ftracking.sspt123 to C/Fortran array" );
  } else {
    xg = (double *)(capi_xg_tmp->data);

  /* Processing variable ie */
  ie_Dims[0]=nnde*nel;
  capi_ie_intent |= F2PY_INTENT_IN;
  capi_ie_tmp = array_from_pyobj(PyArray_INT,ie_Dims,ie_Rank,capi_ie_intent,ie_capi);
  if (capi_ie_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 13rd argument `ie' of ftracking.sspt123 to C/Fortran array" );
  } else {
    ie = (int *)(capi_ie_tmp->data);

  /* Processing variable vtl2g */
  vtl2g_Dims[0]=neq*nnde*nel;
  capi_vtl2g_intent |= F2PY_INTENT_IN;
  capi_vtl2g_tmp = array_from_pyobj(PyArray_INT,vtl2g_Dims,vtl2g_Rank,capi_vtl2g_intent,vtl2g_capi);
  if (capi_vtl2g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 16th argument `vtl2g' of ftracking.sspt123 to C/Fortran array" );
  } else {
    vtl2g = (int *)(capi_vtl2g_tmp->data);

  /* Processing variable npt */
  if (npt_capi == Py_None) npt = len(t_i); else
    f2py_success = int_from_pyobj(&npt,npt_capi,"ftracking.sspt123() 5th argument (npt) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(t_i)>=npt,"len(t_i)>=npt","5th argument npt","sspt123:npt=%d",npt) {
  /* Processing variable tpt */
  tpt_Dims[0]=npt;
  capi_tpt_intent |= F2PY_INTENT_INPLACE;
  capi_tpt_tmp = array_from_pyobj(PyArray_DOUBLE,tpt_Dims,tpt_Rank,capi_tpt_intent,tpt_capi);
  if (capi_tpt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 20th argument `tpt' of ftracking.sspt123 to C/Fortran array" );
  } else {
    tpt = (double *)(capi_tpt_tmp->data);

  /* Processing variable x_i */
  x_i_Dims[0]=maxeq*npt;
  capi_x_i_intent |= F2PY_INTENT_IN;
  capi_x_i_tmp = array_from_pyobj(PyArray_DOUBLE,x_i_Dims,x_i_Rank,capi_x_i_intent,x_i_capi);
  if (capi_x_i_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 18th argument `x_i' of ftracking.sspt123 to C/Fortran array" );
  } else {
    x_i = (double *)(capi_x_i_tmp->data);

  /* Processing variable xpt */
  xpt_Dims[0]=maxeq*npt;
  capi_xpt_intent |= F2PY_INTENT_INPLACE;
  capi_xpt_tmp = array_from_pyobj(PyArray_DOUBLE,xpt_Dims,xpt_Rank,capi_xpt_intent,xpt_capi);
  if (capi_xpt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 23rd argument `xpt' of ftracking.sspt123 to C/Fortran array" );
  } else {
    xpt = (double *)(capi_xpt_tmp->data);

  /* Processing variable mpt */
  mpt_Dims[0]=npt;
  capi_mpt_intent |= F2PY_INTENT_INPLACE;
  capi_mpt_tmp = array_from_pyobj(PyArray_INT,mpt_Dims,mpt_Rank,capi_mpt_intent,mpt_capi);
  if (capi_mpt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 21st argument `mpt' of ftracking.sspt123 to C/Fortran array" );
  } else {
    mpt = (int *)(capi_mpt_tmp->data);

  /* Processing variable idpt */
  idpt_Dims[0]=npt;
  capi_idpt_intent |= F2PY_INTENT_INPLACE;
  capi_idpt_tmp = array_from_pyobj(PyArray_INT,idpt_Dims,idpt_Rank,capi_idpt_intent,idpt_capi);
  if (capi_idpt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 22nd argument `idpt' of ftracking.sspt123 to C/Fortran array" );
  } else {
    idpt = (int *)(capi_idpt_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&maxeq,&nnp,&nel,&nnde,&neq,&npt,&ibf,&lu_o,&atol,&rtol,&sf,&dn_safe,xg,ie,nlrl,lrl,vtl2g,vt1e,x_i,t_i,tpt,mpt,idpt,xpt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_idpt_tmp!=idpt_capi) {
    Py_XDECREF(capi_idpt_tmp); }
  }  /*if (capi_idpt_tmp == NULL) ... else of idpt*/
  /* End of cleaning variable idpt */
  if((PyObject *)capi_mpt_tmp!=mpt_capi) {
    Py_XDECREF(capi_mpt_tmp); }
  }  /*if (capi_mpt_tmp == NULL) ... else of mpt*/
  /* End of cleaning variable mpt */
  if((PyObject *)capi_xpt_tmp!=xpt_capi) {
    Py_XDECREF(capi_xpt_tmp); }
  }  /*if (capi_xpt_tmp == NULL) ... else of xpt*/
  /* End of cleaning variable xpt */
  if((PyObject *)capi_x_i_tmp!=x_i_capi) {
    Py_XDECREF(capi_x_i_tmp); }
  }  /*if (capi_x_i_tmp == NULL) ... else of x_i*/
  /* End of cleaning variable x_i */
  if((PyObject *)capi_tpt_tmp!=tpt_capi) {
    Py_XDECREF(capi_tpt_tmp); }
  }  /*if (capi_tpt_tmp == NULL) ... else of tpt*/
  /* End of cleaning variable tpt */
  } /*CHECKSCALAR(len(t_i)>=npt)*/
  } /*if (f2py_success) of npt*/
  /* End of cleaning variable npt */
  if((PyObject *)capi_vtl2g_tmp!=vtl2g_capi) {
    Py_XDECREF(capi_vtl2g_tmp); }
  }  /*if (capi_vtl2g_tmp == NULL) ... else of vtl2g*/
  /* End of cleaning variable vtl2g */
  if((PyObject *)capi_ie_tmp!=ie_capi) {
    Py_XDECREF(capi_ie_tmp); }
  }  /*if (capi_ie_tmp == NULL) ... else of ie*/
  /* End of cleaning variable ie */
  if((PyObject *)capi_xg_tmp!=xg_capi) {
    Py_XDECREF(capi_xg_tmp); }
  }  /*if (capi_xg_tmp == NULL) ... else of xg*/
  /* End of cleaning variable xg */
  } /*if (f2py_success) of sf*/
  /* End of cleaning variable sf */
  } /*if (f2py_success) of nnde*/
  /* End of cleaning variable nnde */
  if((PyObject *)capi_vt1e_tmp!=vt1e_capi) {
    Py_XDECREF(capi_vt1e_tmp); }
  }  /*if (capi_vt1e_tmp == NULL) ... else of vt1e*/
  /* End of cleaning variable vt1e */
  } /*if (f2py_success) of lu_o*/
  /* End of cleaning variable lu_o */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  if((PyObject *)capi_t_i_tmp!=t_i_capi) {
    Py_XDECREF(capi_t_i_tmp); }
  }  /*if (capi_t_i_tmp == NULL) ... else of t_i*/
  /* End of cleaning variable t_i */
  } /*if (f2py_success) of nel*/
  /* End of cleaning variable nel */
  } /*if (f2py_success) of nnp*/
  /* End of cleaning variable nnp */
  } /*if (f2py_success) of maxeq*/
  /* End of cleaning variable maxeq */
  } /*if (f2py_success) of ibf*/
  /* End of cleaning variable ibf */
  if((PyObject *)capi_nlrl_tmp!=nlrl_capi) {
    Py_XDECREF(capi_nlrl_tmp); }
  }  /*if (capi_nlrl_tmp == NULL) ... else of nlrl*/
  /* End of cleaning variable nlrl */
  } /*if (f2py_success) of atol*/
  /* End of cleaning variable atol */
  if((PyObject *)capi_lrl_tmp!=lrl_capi) {
    Py_XDECREF(capi_lrl_tmp); }
  }  /*if (capi_lrl_tmp == NULL) ... else of lrl*/
  /* End of cleaning variable lrl */
  } /*if (f2py_success) of rtol*/
  /* End of cleaning variable rtol */
  } /*if (f2py_success) of dn_safe*/
  /* End of cleaning variable dn_safe */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of sspt123 *******************************/

/********************************* eltrak123 *********************************/
static char doc_f2py_rout_ftracking_eltrak123[] = "\
Function signature:\n\
  eltrak123(neq,node,ipt,t1,t2,deq,atol,rtol,sf,dn_safe,xw,vt1w,vt2w,t,dt0,sdt,xs,ak1,ak2,ak3,ak4,ak5,ak6,xtemp,xout5,xout4,xerr,dn_s,dn,idsdt,xpt,tpt,i1,i2,i3,[maxeq,maxnd,maxpt])\n\
Required arguments:\n"
"  neq : input int\n"
"  node : input int\n"
"  ipt : input int\n"
"  t1 : input float\n"
"  t2 : input float\n"
"  deq : input float\n"
"  atol : input float\n"
"  rtol : input float\n"
"  sf : input float\n"
"  dn_safe : input float\n"
"  xw : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  vt1w : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  vt2w : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  t : input float\n"
"  dt0 : input float\n"
"  sdt : input float\n"
"  xs : input rank-1 array('d') with bounds (maxeq)\n"
"  ak1 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak2 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak3 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak4 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak5 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak6 : input rank-1 array('d') with bounds (maxeq)\n"
"  xtemp : input rank-1 array('d') with bounds (maxeq)\n"
"  xout5 : input rank-1 array('d') with bounds (maxeq)\n"
"  xout4 : input rank-1 array('d') with bounds (maxeq)\n"
"  xerr : input rank-1 array('d') with bounds (maxeq)\n"
"  dn_s : input rank-1 array('d') with bounds (maxnd)\n"
"  dn : input rank-1 array('d') with bounds (maxnd)\n"
"  idsdt : input int\n"
"  xpt : input rank-1 array('d') with bounds (maxeq*maxpt)\n"
"  tpt : input rank-1 array('d') with bounds (maxpt)\n"
"  i1 : input int\n"
"  i2 : input int\n"
"  i3 : input int\n"
"Optional arguments:\n"
"  maxeq := shape(xw,0) input int\n"
"  maxnd := shape(xw,1) input int\n"
"  maxpt := len(tpt) input int";
/* extern void F_FUNC(eltrak123,ELTRAK123)(int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_ftracking_eltrak123(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int maxeq = 0;
  PyObject *maxeq_capi = Py_None;
  int maxnd = 0;
  PyObject *maxnd_capi = Py_None;
  int maxpt = 0;
  PyObject *maxpt_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  int node = 0;
  PyObject *node_capi = Py_None;
  int ipt = 0;
  PyObject *ipt_capi = Py_None;
  double t1 = 0;
  PyObject *t1_capi = Py_None;
  double t2 = 0;
  PyObject *t2_capi = Py_None;
  double deq = 0;
  PyObject *deq_capi = Py_None;
  double atol = 0;
  PyObject *atol_capi = Py_None;
  double rtol = 0;
  PyObject *rtol_capi = Py_None;
  double sf = 0;
  PyObject *sf_capi = Py_None;
  double dn_safe = 0;
  PyObject *dn_safe_capi = Py_None;
  double *xw = NULL;
  npy_intp xw_Dims[2] = {-1, -1};
  const int xw_Rank = 2;
  PyArrayObject *capi_xw_tmp = NULL;
  int capi_xw_intent = 0;
  PyObject *xw_capi = Py_None;
  double *vt1w = NULL;
  npy_intp vt1w_Dims[2] = {-1, -1};
  const int vt1w_Rank = 2;
  PyArrayObject *capi_vt1w_tmp = NULL;
  int capi_vt1w_intent = 0;
  PyObject *vt1w_capi = Py_None;
  double *vt2w = NULL;
  npy_intp vt2w_Dims[2] = {-1, -1};
  const int vt2w_Rank = 2;
  PyArrayObject *capi_vt2w_tmp = NULL;
  int capi_vt2w_intent = 0;
  PyObject *vt2w_capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  double dt0 = 0;
  PyObject *dt0_capi = Py_None;
  double sdt = 0;
  PyObject *sdt_capi = Py_None;
  double *xs = NULL;
  npy_intp xs_Dims[1] = {-1};
  const int xs_Rank = 1;
  PyArrayObject *capi_xs_tmp = NULL;
  int capi_xs_intent = 0;
  PyObject *xs_capi = Py_None;
  double *ak1 = NULL;
  npy_intp ak1_Dims[1] = {-1};
  const int ak1_Rank = 1;
  PyArrayObject *capi_ak1_tmp = NULL;
  int capi_ak1_intent = 0;
  PyObject *ak1_capi = Py_None;
  double *ak2 = NULL;
  npy_intp ak2_Dims[1] = {-1};
  const int ak2_Rank = 1;
  PyArrayObject *capi_ak2_tmp = NULL;
  int capi_ak2_intent = 0;
  PyObject *ak2_capi = Py_None;
  double *ak3 = NULL;
  npy_intp ak3_Dims[1] = {-1};
  const int ak3_Rank = 1;
  PyArrayObject *capi_ak3_tmp = NULL;
  int capi_ak3_intent = 0;
  PyObject *ak3_capi = Py_None;
  double *ak4 = NULL;
  npy_intp ak4_Dims[1] = {-1};
  const int ak4_Rank = 1;
  PyArrayObject *capi_ak4_tmp = NULL;
  int capi_ak4_intent = 0;
  PyObject *ak4_capi = Py_None;
  double *ak5 = NULL;
  npy_intp ak5_Dims[1] = {-1};
  const int ak5_Rank = 1;
  PyArrayObject *capi_ak5_tmp = NULL;
  int capi_ak5_intent = 0;
  PyObject *ak5_capi = Py_None;
  double *ak6 = NULL;
  npy_intp ak6_Dims[1] = {-1};
  const int ak6_Rank = 1;
  PyArrayObject *capi_ak6_tmp = NULL;
  int capi_ak6_intent = 0;
  PyObject *ak6_capi = Py_None;
  double *xtemp = NULL;
  npy_intp xtemp_Dims[1] = {-1};
  const int xtemp_Rank = 1;
  PyArrayObject *capi_xtemp_tmp = NULL;
  int capi_xtemp_intent = 0;
  PyObject *xtemp_capi = Py_None;
  double *xout5 = NULL;
  npy_intp xout5_Dims[1] = {-1};
  const int xout5_Rank = 1;
  PyArrayObject *capi_xout5_tmp = NULL;
  int capi_xout5_intent = 0;
  PyObject *xout5_capi = Py_None;
  double *xout4 = NULL;
  npy_intp xout4_Dims[1] = {-1};
  const int xout4_Rank = 1;
  PyArrayObject *capi_xout4_tmp = NULL;
  int capi_xout4_intent = 0;
  PyObject *xout4_capi = Py_None;
  double *xerr = NULL;
  npy_intp xerr_Dims[1] = {-1};
  const int xerr_Rank = 1;
  PyArrayObject *capi_xerr_tmp = NULL;
  int capi_xerr_intent = 0;
  PyObject *xerr_capi = Py_None;
  double *dn_s = NULL;
  npy_intp dn_s_Dims[1] = {-1};
  const int dn_s_Rank = 1;
  PyArrayObject *capi_dn_s_tmp = NULL;
  int capi_dn_s_intent = 0;
  PyObject *dn_s_capi = Py_None;
  double *dn = NULL;
  npy_intp dn_Dims[1] = {-1};
  const int dn_Rank = 1;
  PyArrayObject *capi_dn_tmp = NULL;
  int capi_dn_intent = 0;
  PyObject *dn_capi = Py_None;
  int idsdt = 0;
  PyObject *idsdt_capi = Py_None;
  double *xpt = NULL;
  npy_intp xpt_Dims[1] = {-1};
  const int xpt_Rank = 1;
  PyArrayObject *capi_xpt_tmp = NULL;
  int capi_xpt_intent = 0;
  PyObject *xpt_capi = Py_None;
  double *tpt = NULL;
  npy_intp tpt_Dims[1] = {-1};
  const int tpt_Rank = 1;
  PyArrayObject *capi_tpt_tmp = NULL;
  int capi_tpt_intent = 0;
  PyObject *tpt_capi = Py_None;
  int i1 = 0;
  PyObject *i1_capi = Py_None;
  int i2 = 0;
  PyObject *i2_capi = Py_None;
  int i3 = 0;
  PyObject *i3_capi = Py_None;
  static char *capi_kwlist[] = {"neq","node","ipt","t1","t2","deq","atol","rtol","sf","dn_safe","xw","vt1w","vt2w","t","dt0","sdt","xs","ak1","ak2","ak3","ak4","ak5","ak6","xtemp","xout5","xout4","xerr","dn_s","dn","idsdt","xpt","tpt","i1","i2","i3","maxeq","maxnd","maxpt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOO:ftracking.eltrak123",\
    capi_kwlist,&neq_capi,&node_capi,&ipt_capi,&t1_capi,&t2_capi,&deq_capi,&atol_capi,&rtol_capi,&sf_capi,&dn_safe_capi,&xw_capi,&vt1w_capi,&vt2w_capi,&t_capi,&dt0_capi,&sdt_capi,&xs_capi,&ak1_capi,&ak2_capi,&ak3_capi,&ak4_capi,&ak5_capi,&ak6_capi,&xtemp_capi,&xout5_capi,&xout4_capi,&xerr_capi,&dn_s_capi,&dn_capi,&idsdt_capi,&xpt_capi,&tpt_capi,&i1_capi,&i2_capi,&i3_capi,&maxeq_capi,&maxnd_capi,&maxpt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable sdt */
    f2py_success = double_from_pyobj(&sdt,sdt_capi,"ftracking.eltrak123() 16th argument (sdt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dn_safe */
    f2py_success = double_from_pyobj(&dn_safe,dn_safe_capi,"ftracking.eltrak123() 10th argument (dn_safe) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ipt */
    f2py_success = int_from_pyobj(&ipt,ipt_capi,"ftracking.eltrak123() 3rd argument (ipt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable xw */
  ;
  capi_xw_intent |= F2PY_INTENT_IN;
  capi_xw_tmp = array_from_pyobj(PyArray_DOUBLE,xw_Dims,xw_Rank,capi_xw_intent,xw_capi);
  if (capi_xw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 11st argument `xw' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xw = (double *)(capi_xw_tmp->data);

  /* Processing variable rtol */
    f2py_success = double_from_pyobj(&rtol,rtol_capi,"ftracking.eltrak123() 8th argument (rtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dt0 */
    f2py_success = double_from_pyobj(&dt0,dt0_capi,"ftracking.eltrak123() 15th argument (dt0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable node */
    f2py_success = int_from_pyobj(&node,node_capi,"ftracking.eltrak123() 2nd argument (node) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i1 */
    f2py_success = int_from_pyobj(&i1,i1_capi,"ftracking.eltrak123() 33rd argument (i1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i3 */
    f2py_success = int_from_pyobj(&i3,i3_capi,"ftracking.eltrak123() 35th argument (i3) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i2 */
    f2py_success = int_from_pyobj(&i2,i2_capi,"ftracking.eltrak123() 34th argument (i2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable atol */
    f2py_success = double_from_pyobj(&atol,atol_capi,"ftracking.eltrak123() 7th argument (atol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t2 */
    f2py_success = double_from_pyobj(&t2,t2_capi,"ftracking.eltrak123() 5th argument (t2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.eltrak123() 1st argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable t1 */
    f2py_success = double_from_pyobj(&t1,t1_capi,"ftracking.eltrak123() 4th argument (t1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tpt */
  ;
  capi_tpt_intent |= F2PY_INTENT_IN;
  capi_tpt_tmp = array_from_pyobj(PyArray_DOUBLE,tpt_Dims,tpt_Rank,capi_tpt_intent,tpt_capi);
  if (capi_tpt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 32nd argument `tpt' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    tpt = (double *)(capi_tpt_tmp->data);

  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"ftracking.eltrak123() 14th argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable deq */
    f2py_success = double_from_pyobj(&deq,deq_capi,"ftracking.eltrak123() 6th argument (deq) can't be converted to double");
  if (f2py_success) {
  /* Processing variable idsdt */
    f2py_success = int_from_pyobj(&idsdt,idsdt_capi,"ftracking.eltrak123() 30th argument (idsdt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable sf */
    f2py_success = double_from_pyobj(&sf,sf_capi,"ftracking.eltrak123() 9th argument (sf) can't be converted to double");
  if (f2py_success) {
  /* Processing variable maxeq */
  if (maxeq_capi == Py_None) maxeq = shape(xw,0); else
    f2py_success = int_from_pyobj(&maxeq,maxeq_capi,"ftracking.eltrak123() 1st keyword (maxeq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xw,0)==maxeq,"shape(xw,0)==maxeq","1st keyword maxeq","eltrak123:maxeq=%d",maxeq) {
  /* Processing variable xerr */
  xerr_Dims[0]=maxeq;
  capi_xerr_intent |= F2PY_INTENT_IN;
  capi_xerr_tmp = array_from_pyobj(PyArray_DOUBLE,xerr_Dims,xerr_Rank,capi_xerr_intent,xerr_capi);
  if (capi_xerr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 27th argument `xerr' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xerr = (double *)(capi_xerr_tmp->data);

  /* Processing variable xout5 */
  xout5_Dims[0]=maxeq;
  capi_xout5_intent |= F2PY_INTENT_IN;
  capi_xout5_tmp = array_from_pyobj(PyArray_DOUBLE,xout5_Dims,xout5_Rank,capi_xout5_intent,xout5_capi);
  if (capi_xout5_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 25th argument `xout5' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xout5 = (double *)(capi_xout5_tmp->data);

  /* Processing variable xout4 */
  xout4_Dims[0]=maxeq;
  capi_xout4_intent |= F2PY_INTENT_IN;
  capi_xout4_tmp = array_from_pyobj(PyArray_DOUBLE,xout4_Dims,xout4_Rank,capi_xout4_intent,xout4_capi);
  if (capi_xout4_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 26th argument `xout4' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xout4 = (double *)(capi_xout4_tmp->data);

  /* Processing variable xs */
  xs_Dims[0]=maxeq;
  capi_xs_intent |= F2PY_INTENT_IN;
  capi_xs_tmp = array_from_pyobj(PyArray_DOUBLE,xs_Dims,xs_Rank,capi_xs_intent,xs_capi);
  if (capi_xs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 17th argument `xs' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xs = (double *)(capi_xs_tmp->data);

  /* Processing variable ak3 */
  ak3_Dims[0]=maxeq;
  capi_ak3_intent |= F2PY_INTENT_IN;
  capi_ak3_tmp = array_from_pyobj(PyArray_DOUBLE,ak3_Dims,ak3_Rank,capi_ak3_intent,ak3_capi);
  if (capi_ak3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 20th argument `ak3' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    ak3 = (double *)(capi_ak3_tmp->data);

  /* Processing variable ak2 */
  ak2_Dims[0]=maxeq;
  capi_ak2_intent |= F2PY_INTENT_IN;
  capi_ak2_tmp = array_from_pyobj(PyArray_DOUBLE,ak2_Dims,ak2_Rank,capi_ak2_intent,ak2_capi);
  if (capi_ak2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 19th argument `ak2' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    ak2 = (double *)(capi_ak2_tmp->data);

  /* Processing variable ak1 */
  ak1_Dims[0]=maxeq;
  capi_ak1_intent |= F2PY_INTENT_IN;
  capi_ak1_tmp = array_from_pyobj(PyArray_DOUBLE,ak1_Dims,ak1_Rank,capi_ak1_intent,ak1_capi);
  if (capi_ak1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 18th argument `ak1' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    ak1 = (double *)(capi_ak1_tmp->data);

  /* Processing variable ak6 */
  ak6_Dims[0]=maxeq;
  capi_ak6_intent |= F2PY_INTENT_IN;
  capi_ak6_tmp = array_from_pyobj(PyArray_DOUBLE,ak6_Dims,ak6_Rank,capi_ak6_intent,ak6_capi);
  if (capi_ak6_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 23rd argument `ak6' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    ak6 = (double *)(capi_ak6_tmp->data);

  /* Processing variable ak5 */
  ak5_Dims[0]=maxeq;
  capi_ak5_intent |= F2PY_INTENT_IN;
  capi_ak5_tmp = array_from_pyobj(PyArray_DOUBLE,ak5_Dims,ak5_Rank,capi_ak5_intent,ak5_capi);
  if (capi_ak5_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 22nd argument `ak5' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    ak5 = (double *)(capi_ak5_tmp->data);

  /* Processing variable ak4 */
  ak4_Dims[0]=maxeq;
  capi_ak4_intent |= F2PY_INTENT_IN;
  capi_ak4_tmp = array_from_pyobj(PyArray_DOUBLE,ak4_Dims,ak4_Rank,capi_ak4_intent,ak4_capi);
  if (capi_ak4_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 21st argument `ak4' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    ak4 = (double *)(capi_ak4_tmp->data);

  /* Processing variable xtemp */
  xtemp_Dims[0]=maxeq;
  capi_xtemp_intent |= F2PY_INTENT_IN;
  capi_xtemp_tmp = array_from_pyobj(PyArray_DOUBLE,xtemp_Dims,xtemp_Rank,capi_xtemp_intent,xtemp_capi);
  if (capi_xtemp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 24th argument `xtemp' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xtemp = (double *)(capi_xtemp_tmp->data);

  /* Processing variable maxpt */
  if (maxpt_capi == Py_None) maxpt = len(tpt); else
    f2py_success = int_from_pyobj(&maxpt,maxpt_capi,"ftracking.eltrak123() 3rd keyword (maxpt) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(tpt)>=maxpt,"len(tpt)>=maxpt","3rd keyword maxpt","eltrak123:maxpt=%d",maxpt) {
  /* Processing variable maxnd */
  if (maxnd_capi == Py_None) maxnd = shape(xw,1); else
    f2py_success = int_from_pyobj(&maxnd,maxnd_capi,"ftracking.eltrak123() 2nd keyword (maxnd) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xw,1)==maxnd,"shape(xw,1)==maxnd","2nd keyword maxnd","eltrak123:maxnd=%d",maxnd) {
  /* Processing variable dn */
  dn_Dims[0]=maxnd;
  capi_dn_intent |= F2PY_INTENT_IN;
  capi_dn_tmp = array_from_pyobj(PyArray_DOUBLE,dn_Dims,dn_Rank,capi_dn_intent,dn_capi);
  if (capi_dn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 29th argument `dn' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    dn = (double *)(capi_dn_tmp->data);

  /* Processing variable dn_s */
  dn_s_Dims[0]=maxnd;
  capi_dn_s_intent |= F2PY_INTENT_IN;
  capi_dn_s_tmp = array_from_pyobj(PyArray_DOUBLE,dn_s_Dims,dn_s_Rank,capi_dn_s_intent,dn_s_capi);
  if (capi_dn_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 28th argument `dn_s' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    dn_s = (double *)(capi_dn_s_tmp->data);

  /* Processing variable vt2w */
  vt2w_Dims[0]=maxeq,vt2w_Dims[1]=maxnd;
  capi_vt2w_intent |= F2PY_INTENT_IN;
  capi_vt2w_tmp = array_from_pyobj(PyArray_DOUBLE,vt2w_Dims,vt2w_Rank,capi_vt2w_intent,vt2w_capi);
  if (capi_vt2w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 13rd argument `vt2w' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    vt2w = (double *)(capi_vt2w_tmp->data);

  /* Processing variable xpt */
  xpt_Dims[0]=maxeq*maxpt;
  capi_xpt_intent |= F2PY_INTENT_IN;
  capi_xpt_tmp = array_from_pyobj(PyArray_DOUBLE,xpt_Dims,xpt_Rank,capi_xpt_intent,xpt_capi);
  if (capi_xpt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 31st argument `xpt' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    xpt = (double *)(capi_xpt_tmp->data);

  /* Processing variable vt1w */
  vt1w_Dims[0]=maxeq,vt1w_Dims[1]=maxnd;
  capi_vt1w_intent |= F2PY_INTENT_IN;
  capi_vt1w_tmp = array_from_pyobj(PyArray_DOUBLE,vt1w_Dims,vt1w_Rank,capi_vt1w_intent,vt1w_capi);
  if (capi_vt1w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 12nd argument `vt1w' of ftracking.eltrak123 to C/Fortran array" );
  } else {
    vt1w = (double *)(capi_vt1w_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&maxeq,&maxnd,&maxpt,&neq,&node,&ipt,&t1,&t2,&deq,&atol,&rtol,&sf,&dn_safe,xw,vt1w,vt2w,&t,&dt0,&sdt,xs,ak1,ak2,ak3,ak4,ak5,ak6,xtemp,xout5,xout4,xerr,dn_s,dn,&idsdt,xpt,tpt,&i1,&i2,&i3);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vt1w_tmp!=vt1w_capi) {
    Py_XDECREF(capi_vt1w_tmp); }
  }  /*if (capi_vt1w_tmp == NULL) ... else of vt1w*/
  /* End of cleaning variable vt1w */
  if((PyObject *)capi_xpt_tmp!=xpt_capi) {
    Py_XDECREF(capi_xpt_tmp); }
  }  /*if (capi_xpt_tmp == NULL) ... else of xpt*/
  /* End of cleaning variable xpt */
  if((PyObject *)capi_vt2w_tmp!=vt2w_capi) {
    Py_XDECREF(capi_vt2w_tmp); }
  }  /*if (capi_vt2w_tmp == NULL) ... else of vt2w*/
  /* End of cleaning variable vt2w */
  if((PyObject *)capi_dn_s_tmp!=dn_s_capi) {
    Py_XDECREF(capi_dn_s_tmp); }
  }  /*if (capi_dn_s_tmp == NULL) ... else of dn_s*/
  /* End of cleaning variable dn_s */
  if((PyObject *)capi_dn_tmp!=dn_capi) {
    Py_XDECREF(capi_dn_tmp); }
  }  /*if (capi_dn_tmp == NULL) ... else of dn*/
  /* End of cleaning variable dn */
  } /*CHECKSCALAR(shape(xw,1)==maxnd)*/
  } /*if (f2py_success) of maxnd*/
  /* End of cleaning variable maxnd */
  } /*CHECKSCALAR(len(tpt)>=maxpt)*/
  } /*if (f2py_success) of maxpt*/
  /* End of cleaning variable maxpt */
  if((PyObject *)capi_xtemp_tmp!=xtemp_capi) {
    Py_XDECREF(capi_xtemp_tmp); }
  }  /*if (capi_xtemp_tmp == NULL) ... else of xtemp*/
  /* End of cleaning variable xtemp */
  if((PyObject *)capi_ak4_tmp!=ak4_capi) {
    Py_XDECREF(capi_ak4_tmp); }
  }  /*if (capi_ak4_tmp == NULL) ... else of ak4*/
  /* End of cleaning variable ak4 */
  if((PyObject *)capi_ak5_tmp!=ak5_capi) {
    Py_XDECREF(capi_ak5_tmp); }
  }  /*if (capi_ak5_tmp == NULL) ... else of ak5*/
  /* End of cleaning variable ak5 */
  if((PyObject *)capi_ak6_tmp!=ak6_capi) {
    Py_XDECREF(capi_ak6_tmp); }
  }  /*if (capi_ak6_tmp == NULL) ... else of ak6*/
  /* End of cleaning variable ak6 */
  if((PyObject *)capi_ak1_tmp!=ak1_capi) {
    Py_XDECREF(capi_ak1_tmp); }
  }  /*if (capi_ak1_tmp == NULL) ... else of ak1*/
  /* End of cleaning variable ak1 */
  if((PyObject *)capi_ak2_tmp!=ak2_capi) {
    Py_XDECREF(capi_ak2_tmp); }
  }  /*if (capi_ak2_tmp == NULL) ... else of ak2*/
  /* End of cleaning variable ak2 */
  if((PyObject *)capi_ak3_tmp!=ak3_capi) {
    Py_XDECREF(capi_ak3_tmp); }
  }  /*if (capi_ak3_tmp == NULL) ... else of ak3*/
  /* End of cleaning variable ak3 */
  if((PyObject *)capi_xs_tmp!=xs_capi) {
    Py_XDECREF(capi_xs_tmp); }
  }  /*if (capi_xs_tmp == NULL) ... else of xs*/
  /* End of cleaning variable xs */
  if((PyObject *)capi_xout4_tmp!=xout4_capi) {
    Py_XDECREF(capi_xout4_tmp); }
  }  /*if (capi_xout4_tmp == NULL) ... else of xout4*/
  /* End of cleaning variable xout4 */
  if((PyObject *)capi_xout5_tmp!=xout5_capi) {
    Py_XDECREF(capi_xout5_tmp); }
  }  /*if (capi_xout5_tmp == NULL) ... else of xout5*/
  /* End of cleaning variable xout5 */
  if((PyObject *)capi_xerr_tmp!=xerr_capi) {
    Py_XDECREF(capi_xerr_tmp); }
  }  /*if (capi_xerr_tmp == NULL) ... else of xerr*/
  /* End of cleaning variable xerr */
  } /*CHECKSCALAR(shape(xw,0)==maxeq)*/
  } /*if (f2py_success) of maxeq*/
  /* End of cleaning variable maxeq */
  } /*if (f2py_success) of sf*/
  /* End of cleaning variable sf */
  } /*if (f2py_success) of idsdt*/
  /* End of cleaning variable idsdt */
  } /*if (f2py_success) of deq*/
  /* End of cleaning variable deq */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
  if((PyObject *)capi_tpt_tmp!=tpt_capi) {
    Py_XDECREF(capi_tpt_tmp); }
  }  /*if (capi_tpt_tmp == NULL) ... else of tpt*/
  /* End of cleaning variable tpt */
  } /*if (f2py_success) of t1*/
  /* End of cleaning variable t1 */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  } /*if (f2py_success) of t2*/
  /* End of cleaning variable t2 */
  } /*if (f2py_success) of atol*/
  /* End of cleaning variable atol */
  } /*if (f2py_success) of i2*/
  /* End of cleaning variable i2 */
  } /*if (f2py_success) of i3*/
  /* End of cleaning variable i3 */
  } /*if (f2py_success) of i1*/
  /* End of cleaning variable i1 */
  } /*if (f2py_success) of node*/
  /* End of cleaning variable node */
  } /*if (f2py_success) of dt0*/
  /* End of cleaning variable dt0 */
  } /*if (f2py_success) of rtol*/
  /* End of cleaning variable rtol */
  if((PyObject *)capi_xw_tmp!=xw_capi) {
    Py_XDECREF(capi_xw_tmp); }
  }  /*if (capi_xw_tmp == NULL) ... else of xw*/
  /* End of cleaning variable xw */
  } /*if (f2py_success) of ipt*/
  /* End of cleaning variable ipt */
  } /*if (f2py_success) of dn_safe*/
  /* End of cleaning variable dn_safe */
  } /*if (f2py_success) of sdt*/
  /* End of cleaning variable sdt */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of eltrak123 ******************************/

/********************************** dn_check **********************************/
static char doc_f2py_rout_ftracking_dn_check[] = "\
Function signature:\n\
  dn_check(node,neq,dl,atol,dn,i1,i2,i3,[maxnd])\n\
Required arguments:\n"
"  node : input int\n"
"  neq : input int\n"
"  dl : input float\n"
"  atol : input float\n"
"  dn : input rank-1 array('d') with bounds (maxnd)\n"
"  i1 : input int\n"
"  i2 : input int\n"
"  i3 : input int\n"
"Optional arguments:\n"
"  maxnd := len(dn) input int";
/* extern void F_FUNC_US(dn_check,DN_CHECK)(int*,int*,int*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_ftracking_dn_check(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int maxnd = 0;
  PyObject *maxnd_capi = Py_None;
  int node = 0;
  PyObject *node_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  double dl = 0;
  PyObject *dl_capi = Py_None;
  double atol = 0;
  PyObject *atol_capi = Py_None;
  double *dn = NULL;
  npy_intp dn_Dims[1] = {-1};
  const int dn_Rank = 1;
  PyArrayObject *capi_dn_tmp = NULL;
  int capi_dn_intent = 0;
  PyObject *dn_capi = Py_None;
  int i1 = 0;
  PyObject *i1_capi = Py_None;
  int i2 = 0;
  PyObject *i2_capi = Py_None;
  int i3 = 0;
  PyObject *i3_capi = Py_None;
  static char *capi_kwlist[] = {"node","neq","dl","atol","dn","i1","i2","i3","maxnd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|O:ftracking.dn_check",\
    capi_kwlist,&node_capi,&neq_capi,&dl_capi,&atol_capi,&dn_capi,&i1_capi,&i2_capi,&i3_capi,&maxnd_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dn */
  ;
  capi_dn_intent |= F2PY_INTENT_IN;
  capi_dn_tmp = array_from_pyobj(PyArray_DOUBLE,dn_Dims,dn_Rank,capi_dn_intent,dn_capi);
  if (capi_dn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 5th argument `dn' of ftracking.dn_check to C/Fortran array" );
  } else {
    dn = (double *)(capi_dn_tmp->data);

  /* Processing variable node */
    f2py_success = int_from_pyobj(&node,node_capi,"ftracking.dn_check() 1st argument (node) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dl */
    f2py_success = double_from_pyobj(&dl,dl_capi,"ftracking.dn_check() 3rd argument (dl) can't be converted to double");
  if (f2py_success) {
  /* Processing variable i1 */
    f2py_success = int_from_pyobj(&i1,i1_capi,"ftracking.dn_check() 6th argument (i1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i3 */
    f2py_success = int_from_pyobj(&i3,i3_capi,"ftracking.dn_check() 8th argument (i3) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i2 */
    f2py_success = int_from_pyobj(&i2,i2_capi,"ftracking.dn_check() 7th argument (i2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable atol */
    f2py_success = double_from_pyobj(&atol,atol_capi,"ftracking.dn_check() 4th argument (atol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.dn_check() 2nd argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxnd */
  if (maxnd_capi == Py_None) maxnd = len(dn); else
    f2py_success = int_from_pyobj(&maxnd,maxnd_capi,"ftracking.dn_check() 1st keyword (maxnd) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(dn)>=maxnd,"len(dn)>=maxnd","1st keyword maxnd","dn_check:maxnd=%d",maxnd) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&maxnd,&node,&neq,&dl,&atol,dn,&i1,&i2,&i3);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(dn)>=maxnd)*/
  } /*if (f2py_success) of maxnd*/
  /* End of cleaning variable maxnd */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  } /*if (f2py_success) of atol*/
  /* End of cleaning variable atol */
  } /*if (f2py_success) of i2*/
  /* End of cleaning variable i2 */
  } /*if (f2py_success) of i3*/
  /* End of cleaning variable i3 */
  } /*if (f2py_success) of i1*/
  /* End of cleaning variable i1 */
  } /*if (f2py_success) of dl*/
  /* End of cleaning variable dl */
  } /*if (f2py_success) of node*/
  /* End of cleaning variable node */
  if((PyObject *)capi_dn_tmp!=dn_capi) {
    Py_XDECREF(capi_dn_tmp); }
  }  /*if (capi_dn_tmp == NULL) ... else of dn*/
  /* End of cleaning variable dn */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of dn_check ******************************/

/********************************** rkck_pt **********************************/
static char doc_f2py_rout_ftracking_rkck_pt[] = "\
Function signature:\n\
  rkck_pt(neq,node,t,dt,t1,t2,xw,vt1w,vt2w,xs,ak1,ak2,ak3,ak4,ak5,ak6,xtemp,xout5,xout4,xerr,dn_s,[maxeq,maxnd])\n\
Required arguments:\n"
"  neq : input int\n"
"  node : input int\n"
"  t : input float\n"
"  dt : input float\n"
"  t1 : input float\n"
"  t2 : input float\n"
"  xw : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  vt1w : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  vt2w : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  xs : input rank-1 array('d') with bounds (maxeq)\n"
"  ak1 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak2 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak3 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak4 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak5 : input rank-1 array('d') with bounds (maxeq)\n"
"  ak6 : input rank-1 array('d') with bounds (maxeq)\n"
"  xtemp : input rank-1 array('d') with bounds (maxeq)\n"
"  xout5 : input rank-1 array('d') with bounds (maxeq)\n"
"  xout4 : input rank-1 array('d') with bounds (maxeq)\n"
"  xerr : input rank-1 array('d') with bounds (maxeq)\n"
"  dn_s : input rank-1 array('d') with bounds (maxnd)\n"
"Optional arguments:\n"
"  maxeq := shape(xw,0) input int\n"
"  maxnd := shape(xw,1) input int";
/* extern void F_FUNC_US(rkck_pt,RKCK_PT)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_ftracking_rkck_pt(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int maxeq = 0;
  PyObject *maxeq_capi = Py_None;
  int maxnd = 0;
  PyObject *maxnd_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  int node = 0;
  PyObject *node_capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  double t1 = 0;
  PyObject *t1_capi = Py_None;
  double t2 = 0;
  PyObject *t2_capi = Py_None;
  double *xw = NULL;
  npy_intp xw_Dims[2] = {-1, -1};
  const int xw_Rank = 2;
  PyArrayObject *capi_xw_tmp = NULL;
  int capi_xw_intent = 0;
  PyObject *xw_capi = Py_None;
  double *vt1w = NULL;
  npy_intp vt1w_Dims[2] = {-1, -1};
  const int vt1w_Rank = 2;
  PyArrayObject *capi_vt1w_tmp = NULL;
  int capi_vt1w_intent = 0;
  PyObject *vt1w_capi = Py_None;
  double *vt2w = NULL;
  npy_intp vt2w_Dims[2] = {-1, -1};
  const int vt2w_Rank = 2;
  PyArrayObject *capi_vt2w_tmp = NULL;
  int capi_vt2w_intent = 0;
  PyObject *vt2w_capi = Py_None;
  double *xs = NULL;
  npy_intp xs_Dims[1] = {-1};
  const int xs_Rank = 1;
  PyArrayObject *capi_xs_tmp = NULL;
  int capi_xs_intent = 0;
  PyObject *xs_capi = Py_None;
  double *ak1 = NULL;
  npy_intp ak1_Dims[1] = {-1};
  const int ak1_Rank = 1;
  PyArrayObject *capi_ak1_tmp = NULL;
  int capi_ak1_intent = 0;
  PyObject *ak1_capi = Py_None;
  double *ak2 = NULL;
  npy_intp ak2_Dims[1] = {-1};
  const int ak2_Rank = 1;
  PyArrayObject *capi_ak2_tmp = NULL;
  int capi_ak2_intent = 0;
  PyObject *ak2_capi = Py_None;
  double *ak3 = NULL;
  npy_intp ak3_Dims[1] = {-1};
  const int ak3_Rank = 1;
  PyArrayObject *capi_ak3_tmp = NULL;
  int capi_ak3_intent = 0;
  PyObject *ak3_capi = Py_None;
  double *ak4 = NULL;
  npy_intp ak4_Dims[1] = {-1};
  const int ak4_Rank = 1;
  PyArrayObject *capi_ak4_tmp = NULL;
  int capi_ak4_intent = 0;
  PyObject *ak4_capi = Py_None;
  double *ak5 = NULL;
  npy_intp ak5_Dims[1] = {-1};
  const int ak5_Rank = 1;
  PyArrayObject *capi_ak5_tmp = NULL;
  int capi_ak5_intent = 0;
  PyObject *ak5_capi = Py_None;
  double *ak6 = NULL;
  npy_intp ak6_Dims[1] = {-1};
  const int ak6_Rank = 1;
  PyArrayObject *capi_ak6_tmp = NULL;
  int capi_ak6_intent = 0;
  PyObject *ak6_capi = Py_None;
  double *xtemp = NULL;
  npy_intp xtemp_Dims[1] = {-1};
  const int xtemp_Rank = 1;
  PyArrayObject *capi_xtemp_tmp = NULL;
  int capi_xtemp_intent = 0;
  PyObject *xtemp_capi = Py_None;
  double *xout5 = NULL;
  npy_intp xout5_Dims[1] = {-1};
  const int xout5_Rank = 1;
  PyArrayObject *capi_xout5_tmp = NULL;
  int capi_xout5_intent = 0;
  PyObject *xout5_capi = Py_None;
  double *xout4 = NULL;
  npy_intp xout4_Dims[1] = {-1};
  const int xout4_Rank = 1;
  PyArrayObject *capi_xout4_tmp = NULL;
  int capi_xout4_intent = 0;
  PyObject *xout4_capi = Py_None;
  double *xerr = NULL;
  npy_intp xerr_Dims[1] = {-1};
  const int xerr_Rank = 1;
  PyArrayObject *capi_xerr_tmp = NULL;
  int capi_xerr_intent = 0;
  PyObject *xerr_capi = Py_None;
  double *dn_s = NULL;
  npy_intp dn_s_Dims[1] = {-1};
  const int dn_s_Rank = 1;
  PyArrayObject *capi_dn_s_tmp = NULL;
  int capi_dn_s_intent = 0;
  PyObject *dn_s_capi = Py_None;
  static char *capi_kwlist[] = {"neq","node","t","dt","t1","t2","xw","vt1w","vt2w","xs","ak1","ak2","ak3","ak4","ak5","ak6","xtemp","xout5","xout4","xerr","dn_s","maxeq","maxnd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOO|OO:ftracking.rkck_pt",\
    capi_kwlist,&neq_capi,&node_capi,&t_capi,&dt_capi,&t1_capi,&t2_capi,&xw_capi,&vt1w_capi,&vt2w_capi,&xs_capi,&ak1_capi,&ak2_capi,&ak3_capi,&ak4_capi,&ak5_capi,&ak6_capi,&xtemp_capi,&xout5_capi,&xout4_capi,&xerr_capi,&dn_s_capi,&maxeq_capi,&maxnd_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable node */
    f2py_success = int_from_pyobj(&node,node_capi,"ftracking.rkck_pt() 2nd argument (node) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"ftracking.rkck_pt() 4th argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t1 */
    f2py_success = double_from_pyobj(&t1,t1_capi,"ftracking.rkck_pt() 5th argument (t1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xw */
  ;
  capi_xw_intent |= F2PY_INTENT_IN;
  capi_xw_tmp = array_from_pyobj(PyArray_DOUBLE,xw_Dims,xw_Rank,capi_xw_intent,xw_capi);
  if (capi_xw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 7th argument `xw' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    xw = (double *)(capi_xw_tmp->data);

  /* Processing variable t2 */
    f2py_success = double_from_pyobj(&t2,t2_capi,"ftracking.rkck_pt() 6th argument (t2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"ftracking.rkck_pt() 3rd argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.rkck_pt() 1st argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxeq */
  if (maxeq_capi == Py_None) maxeq = shape(xw,0); else
    f2py_success = int_from_pyobj(&maxeq,maxeq_capi,"ftracking.rkck_pt() 1st keyword (maxeq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xw,0)==maxeq,"shape(xw,0)==maxeq","1st keyword maxeq","rkck_pt:maxeq=%d",maxeq) {
  /* Processing variable xerr */
  xerr_Dims[0]=maxeq;
  capi_xerr_intent |= F2PY_INTENT_IN;
  capi_xerr_tmp = array_from_pyobj(PyArray_DOUBLE,xerr_Dims,xerr_Rank,capi_xerr_intent,xerr_capi);
  if (capi_xerr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 20th argument `xerr' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    xerr = (double *)(capi_xerr_tmp->data);

  /* Processing variable xout5 */
  xout5_Dims[0]=maxeq;
  capi_xout5_intent |= F2PY_INTENT_IN;
  capi_xout5_tmp = array_from_pyobj(PyArray_DOUBLE,xout5_Dims,xout5_Rank,capi_xout5_intent,xout5_capi);
  if (capi_xout5_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 18th argument `xout5' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    xout5 = (double *)(capi_xout5_tmp->data);

  /* Processing variable xout4 */
  xout4_Dims[0]=maxeq;
  capi_xout4_intent |= F2PY_INTENT_IN;
  capi_xout4_tmp = array_from_pyobj(PyArray_DOUBLE,xout4_Dims,xout4_Rank,capi_xout4_intent,xout4_capi);
  if (capi_xout4_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 19th argument `xout4' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    xout4 = (double *)(capi_xout4_tmp->data);

  /* Processing variable xtemp */
  xtemp_Dims[0]=maxeq;
  capi_xtemp_intent |= F2PY_INTENT_IN;
  capi_xtemp_tmp = array_from_pyobj(PyArray_DOUBLE,xtemp_Dims,xtemp_Rank,capi_xtemp_intent,xtemp_capi);
  if (capi_xtemp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 17th argument `xtemp' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    xtemp = (double *)(capi_xtemp_tmp->data);

  /* Processing variable xs */
  xs_Dims[0]=maxeq;
  capi_xs_intent |= F2PY_INTENT_IN;
  capi_xs_tmp = array_from_pyobj(PyArray_DOUBLE,xs_Dims,xs_Rank,capi_xs_intent,xs_capi);
  if (capi_xs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 10th argument `xs' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    xs = (double *)(capi_xs_tmp->data);

  /* Processing variable ak3 */
  ak3_Dims[0]=maxeq;
  capi_ak3_intent |= F2PY_INTENT_IN;
  capi_ak3_tmp = array_from_pyobj(PyArray_DOUBLE,ak3_Dims,ak3_Rank,capi_ak3_intent,ak3_capi);
  if (capi_ak3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 13rd argument `ak3' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    ak3 = (double *)(capi_ak3_tmp->data);

  /* Processing variable ak2 */
  ak2_Dims[0]=maxeq;
  capi_ak2_intent |= F2PY_INTENT_IN;
  capi_ak2_tmp = array_from_pyobj(PyArray_DOUBLE,ak2_Dims,ak2_Rank,capi_ak2_intent,ak2_capi);
  if (capi_ak2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 12nd argument `ak2' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    ak2 = (double *)(capi_ak2_tmp->data);

  /* Processing variable ak1 */
  ak1_Dims[0]=maxeq;
  capi_ak1_intent |= F2PY_INTENT_IN;
  capi_ak1_tmp = array_from_pyobj(PyArray_DOUBLE,ak1_Dims,ak1_Rank,capi_ak1_intent,ak1_capi);
  if (capi_ak1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 11st argument `ak1' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    ak1 = (double *)(capi_ak1_tmp->data);

  /* Processing variable ak6 */
  ak6_Dims[0]=maxeq;
  capi_ak6_intent |= F2PY_INTENT_IN;
  capi_ak6_tmp = array_from_pyobj(PyArray_DOUBLE,ak6_Dims,ak6_Rank,capi_ak6_intent,ak6_capi);
  if (capi_ak6_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 16th argument `ak6' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    ak6 = (double *)(capi_ak6_tmp->data);

  /* Processing variable ak5 */
  ak5_Dims[0]=maxeq;
  capi_ak5_intent |= F2PY_INTENT_IN;
  capi_ak5_tmp = array_from_pyobj(PyArray_DOUBLE,ak5_Dims,ak5_Rank,capi_ak5_intent,ak5_capi);
  if (capi_ak5_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 15th argument `ak5' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    ak5 = (double *)(capi_ak5_tmp->data);

  /* Processing variable ak4 */
  ak4_Dims[0]=maxeq;
  capi_ak4_intent |= F2PY_INTENT_IN;
  capi_ak4_tmp = array_from_pyobj(PyArray_DOUBLE,ak4_Dims,ak4_Rank,capi_ak4_intent,ak4_capi);
  if (capi_ak4_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 14th argument `ak4' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    ak4 = (double *)(capi_ak4_tmp->data);

  /* Processing variable maxnd */
  if (maxnd_capi == Py_None) maxnd = shape(xw,1); else
    f2py_success = int_from_pyobj(&maxnd,maxnd_capi,"ftracking.rkck_pt() 2nd keyword (maxnd) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xw,1)==maxnd,"shape(xw,1)==maxnd","2nd keyword maxnd","rkck_pt:maxnd=%d",maxnd) {
  /* Processing variable dn_s */
  dn_s_Dims[0]=maxnd;
  capi_dn_s_intent |= F2PY_INTENT_IN;
  capi_dn_s_tmp = array_from_pyobj(PyArray_DOUBLE,dn_s_Dims,dn_s_Rank,capi_dn_s_intent,dn_s_capi);
  if (capi_dn_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 21st argument `dn_s' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    dn_s = (double *)(capi_dn_s_tmp->data);

  /* Processing variable vt1w */
  vt1w_Dims[0]=maxeq,vt1w_Dims[1]=maxnd;
  capi_vt1w_intent |= F2PY_INTENT_IN;
  capi_vt1w_tmp = array_from_pyobj(PyArray_DOUBLE,vt1w_Dims,vt1w_Rank,capi_vt1w_intent,vt1w_capi);
  if (capi_vt1w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 8th argument `vt1w' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    vt1w = (double *)(capi_vt1w_tmp->data);

  /* Processing variable vt2w */
  vt2w_Dims[0]=maxeq,vt2w_Dims[1]=maxnd;
  capi_vt2w_intent |= F2PY_INTENT_IN;
  capi_vt2w_tmp = array_from_pyobj(PyArray_DOUBLE,vt2w_Dims,vt2w_Rank,capi_vt2w_intent,vt2w_capi);
  if (capi_vt2w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 9th argument `vt2w' of ftracking.rkck_pt to C/Fortran array" );
  } else {
    vt2w = (double *)(capi_vt2w_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&maxeq,&maxnd,&neq,&node,&t,&dt,&t1,&t2,xw,vt1w,vt2w,xs,ak1,ak2,ak3,ak4,ak5,ak6,xtemp,xout5,xout4,xerr,dn_s);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vt2w_tmp!=vt2w_capi) {
    Py_XDECREF(capi_vt2w_tmp); }
  }  /*if (capi_vt2w_tmp == NULL) ... else of vt2w*/
  /* End of cleaning variable vt2w */
  if((PyObject *)capi_vt1w_tmp!=vt1w_capi) {
    Py_XDECREF(capi_vt1w_tmp); }
  }  /*if (capi_vt1w_tmp == NULL) ... else of vt1w*/
  /* End of cleaning variable vt1w */
  if((PyObject *)capi_dn_s_tmp!=dn_s_capi) {
    Py_XDECREF(capi_dn_s_tmp); }
  }  /*if (capi_dn_s_tmp == NULL) ... else of dn_s*/
  /* End of cleaning variable dn_s */
  } /*CHECKSCALAR(shape(xw,1)==maxnd)*/
  } /*if (f2py_success) of maxnd*/
  /* End of cleaning variable maxnd */
  if((PyObject *)capi_ak4_tmp!=ak4_capi) {
    Py_XDECREF(capi_ak4_tmp); }
  }  /*if (capi_ak4_tmp == NULL) ... else of ak4*/
  /* End of cleaning variable ak4 */
  if((PyObject *)capi_ak5_tmp!=ak5_capi) {
    Py_XDECREF(capi_ak5_tmp); }
  }  /*if (capi_ak5_tmp == NULL) ... else of ak5*/
  /* End of cleaning variable ak5 */
  if((PyObject *)capi_ak6_tmp!=ak6_capi) {
    Py_XDECREF(capi_ak6_tmp); }
  }  /*if (capi_ak6_tmp == NULL) ... else of ak6*/
  /* End of cleaning variable ak6 */
  if((PyObject *)capi_ak1_tmp!=ak1_capi) {
    Py_XDECREF(capi_ak1_tmp); }
  }  /*if (capi_ak1_tmp == NULL) ... else of ak1*/
  /* End of cleaning variable ak1 */
  if((PyObject *)capi_ak2_tmp!=ak2_capi) {
    Py_XDECREF(capi_ak2_tmp); }
  }  /*if (capi_ak2_tmp == NULL) ... else of ak2*/
  /* End of cleaning variable ak2 */
  if((PyObject *)capi_ak3_tmp!=ak3_capi) {
    Py_XDECREF(capi_ak3_tmp); }
  }  /*if (capi_ak3_tmp == NULL) ... else of ak3*/
  /* End of cleaning variable ak3 */
  if((PyObject *)capi_xs_tmp!=xs_capi) {
    Py_XDECREF(capi_xs_tmp); }
  }  /*if (capi_xs_tmp == NULL) ... else of xs*/
  /* End of cleaning variable xs */
  if((PyObject *)capi_xtemp_tmp!=xtemp_capi) {
    Py_XDECREF(capi_xtemp_tmp); }
  }  /*if (capi_xtemp_tmp == NULL) ... else of xtemp*/
  /* End of cleaning variable xtemp */
  if((PyObject *)capi_xout4_tmp!=xout4_capi) {
    Py_XDECREF(capi_xout4_tmp); }
  }  /*if (capi_xout4_tmp == NULL) ... else of xout4*/
  /* End of cleaning variable xout4 */
  if((PyObject *)capi_xout5_tmp!=xout5_capi) {
    Py_XDECREF(capi_xout5_tmp); }
  }  /*if (capi_xout5_tmp == NULL) ... else of xout5*/
  /* End of cleaning variable xout5 */
  if((PyObject *)capi_xerr_tmp!=xerr_capi) {
    Py_XDECREF(capi_xerr_tmp); }
  }  /*if (capi_xerr_tmp == NULL) ... else of xerr*/
  /* End of cleaning variable xerr */
  } /*CHECKSCALAR(shape(xw,0)==maxeq)*/
  } /*if (f2py_success) of maxeq*/
  /* End of cleaning variable maxeq */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
  } /*if (f2py_success) of t2*/
  /* End of cleaning variable t2 */
  if((PyObject *)capi_xw_tmp!=xw_capi) {
    Py_XDECREF(capi_xw_tmp); }
  }  /*if (capi_xw_tmp == NULL) ... else of xw*/
  /* End of cleaning variable xw */
  } /*if (f2py_success) of t1*/
  /* End of cleaning variable t1 */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of node*/
  /* End of cleaning variable node */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of rkck_pt *******************************/

/*********************************** vel123 ***********************************/
static char doc_f2py_rout_ftracking_vel123[] = "\
Function signature:\n\
  vel123(neq,node,xtemp,tt,t1,t2,xw,vt1w,vt2w,ak,dn,[maxeq,maxnd])\n\
Required arguments:\n"
"  neq : input int\n"
"  node : input int\n"
"  xtemp : input rank-1 array('d') with bounds (maxeq)\n"
"  tt : input float\n"
"  t1 : input float\n"
"  t2 : input float\n"
"  xw : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  vt1w : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  vt2w : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  ak : input rank-1 array('d') with bounds (maxeq)\n"
"  dn : input rank-1 array('d') with bounds (maxnd)\n"
"Optional arguments:\n"
"  maxeq := len(xtemp) input int\n"
"  maxnd := shape(xw,1) input int";
/* extern void F_FUNC(vel123,VEL123)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_ftracking_vel123(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int maxeq = 0;
  PyObject *maxeq_capi = Py_None;
  int maxnd = 0;
  PyObject *maxnd_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  int node = 0;
  PyObject *node_capi = Py_None;
  double *xtemp = NULL;
  npy_intp xtemp_Dims[1] = {-1};
  const int xtemp_Rank = 1;
  PyArrayObject *capi_xtemp_tmp = NULL;
  int capi_xtemp_intent = 0;
  PyObject *xtemp_capi = Py_None;
  double tt = 0;
  PyObject *tt_capi = Py_None;
  double t1 = 0;
  PyObject *t1_capi = Py_None;
  double t2 = 0;
  PyObject *t2_capi = Py_None;
  double *xw = NULL;
  npy_intp xw_Dims[2] = {-1, -1};
  const int xw_Rank = 2;
  PyArrayObject *capi_xw_tmp = NULL;
  int capi_xw_intent = 0;
  PyObject *xw_capi = Py_None;
  double *vt1w = NULL;
  npy_intp vt1w_Dims[2] = {-1, -1};
  const int vt1w_Rank = 2;
  PyArrayObject *capi_vt1w_tmp = NULL;
  int capi_vt1w_intent = 0;
  PyObject *vt1w_capi = Py_None;
  double *vt2w = NULL;
  npy_intp vt2w_Dims[2] = {-1, -1};
  const int vt2w_Rank = 2;
  PyArrayObject *capi_vt2w_tmp = NULL;
  int capi_vt2w_intent = 0;
  PyObject *vt2w_capi = Py_None;
  double *ak = NULL;
  npy_intp ak_Dims[1] = {-1};
  const int ak_Rank = 1;
  PyArrayObject *capi_ak_tmp = NULL;
  int capi_ak_intent = 0;
  PyObject *ak_capi = Py_None;
  double *dn = NULL;
  npy_intp dn_Dims[1] = {-1};
  const int dn_Rank = 1;
  PyArrayObject *capi_dn_tmp = NULL;
  int capi_dn_intent = 0;
  PyObject *dn_capi = Py_None;
  static char *capi_kwlist[] = {"neq","node","xtemp","tt","t1","t2","xw","vt1w","vt2w","ak","dn","maxeq","maxnd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|OO:ftracking.vel123",\
    capi_kwlist,&neq_capi,&node_capi,&xtemp_capi,&tt_capi,&t1_capi,&t2_capi,&xw_capi,&vt1w_capi,&vt2w_capi,&ak_capi,&dn_capi,&maxeq_capi,&maxnd_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable node */
    f2py_success = int_from_pyobj(&node,node_capi,"ftracking.vel123() 2nd argument (node) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tt */
    f2py_success = double_from_pyobj(&tt,tt_capi,"ftracking.vel123() 4th argument (tt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t2 */
    f2py_success = double_from_pyobj(&t2,t2_capi,"ftracking.vel123() 6th argument (t2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t1 */
    f2py_success = double_from_pyobj(&t1,t1_capi,"ftracking.vel123() 5th argument (t1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xtemp */
  ;
  capi_xtemp_intent |= F2PY_INTENT_IN;
  capi_xtemp_tmp = array_from_pyobj(PyArray_DOUBLE,xtemp_Dims,xtemp_Rank,capi_xtemp_intent,xtemp_capi);
  if (capi_xtemp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 3rd argument `xtemp' of ftracking.vel123 to C/Fortran array" );
  } else {
    xtemp = (double *)(capi_xtemp_tmp->data);

  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.vel123() 1st argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxeq */
  if (maxeq_capi == Py_None) maxeq = len(xtemp); else
    f2py_success = int_from_pyobj(&maxeq,maxeq_capi,"ftracking.vel123() 1st keyword (maxeq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xtemp)>=maxeq,"len(xtemp)>=maxeq","1st keyword maxeq","vel123:maxeq=%d",maxeq) {
  /* Processing variable ak */
  ak_Dims[0]=maxeq;
  capi_ak_intent |= F2PY_INTENT_IN;
  capi_ak_tmp = array_from_pyobj(PyArray_DOUBLE,ak_Dims,ak_Rank,capi_ak_intent,ak_capi);
  if (capi_ak_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 10th argument `ak' of ftracking.vel123 to C/Fortran array" );
  } else {
    ak = (double *)(capi_ak_tmp->data);

  /* Processing variable xw */
  xw_Dims[0]=maxeq;
  capi_xw_intent |= F2PY_INTENT_IN;
  capi_xw_tmp = array_from_pyobj(PyArray_DOUBLE,xw_Dims,xw_Rank,capi_xw_intent,xw_capi);
  if (capi_xw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 7th argument `xw' of ftracking.vel123 to C/Fortran array" );
  } else {
    xw = (double *)(capi_xw_tmp->data);

  /* Processing variable maxnd */
  if (maxnd_capi == Py_None) maxnd = shape(xw,1); else
    f2py_success = int_from_pyobj(&maxnd,maxnd_capi,"ftracking.vel123() 2nd keyword (maxnd) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xw,1)==maxnd,"shape(xw,1)==maxnd","2nd keyword maxnd","vel123:maxnd=%d",maxnd) {
  /* Processing variable vt1w */
  vt1w_Dims[0]=maxeq,vt1w_Dims[1]=maxnd;
  capi_vt1w_intent |= F2PY_INTENT_IN;
  capi_vt1w_tmp = array_from_pyobj(PyArray_DOUBLE,vt1w_Dims,vt1w_Rank,capi_vt1w_intent,vt1w_capi);
  if (capi_vt1w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 8th argument `vt1w' of ftracking.vel123 to C/Fortran array" );
  } else {
    vt1w = (double *)(capi_vt1w_tmp->data);

  /* Processing variable dn */
  dn_Dims[0]=maxnd;
  capi_dn_intent |= F2PY_INTENT_IN;
  capi_dn_tmp = array_from_pyobj(PyArray_DOUBLE,dn_Dims,dn_Rank,capi_dn_intent,dn_capi);
  if (capi_dn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 11st argument `dn' of ftracking.vel123 to C/Fortran array" );
  } else {
    dn = (double *)(capi_dn_tmp->data);

  /* Processing variable vt2w */
  vt2w_Dims[0]=maxeq,vt2w_Dims[1]=maxnd;
  capi_vt2w_intent |= F2PY_INTENT_IN;
  capi_vt2w_tmp = array_from_pyobj(PyArray_DOUBLE,vt2w_Dims,vt2w_Rank,capi_vt2w_intent,vt2w_capi);
  if (capi_vt2w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 9th argument `vt2w' of ftracking.vel123 to C/Fortran array" );
  } else {
    vt2w = (double *)(capi_vt2w_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&maxeq,&maxnd,&neq,&node,xtemp,&tt,&t1,&t2,xw,vt1w,vt2w,ak,dn);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vt2w_tmp!=vt2w_capi) {
    Py_XDECREF(capi_vt2w_tmp); }
  }  /*if (capi_vt2w_tmp == NULL) ... else of vt2w*/
  /* End of cleaning variable vt2w */
  if((PyObject *)capi_dn_tmp!=dn_capi) {
    Py_XDECREF(capi_dn_tmp); }
  }  /*if (capi_dn_tmp == NULL) ... else of dn*/
  /* End of cleaning variable dn */
  if((PyObject *)capi_vt1w_tmp!=vt1w_capi) {
    Py_XDECREF(capi_vt1w_tmp); }
  }  /*if (capi_vt1w_tmp == NULL) ... else of vt1w*/
  /* End of cleaning variable vt1w */
  } /*CHECKSCALAR(shape(xw,1)==maxnd)*/
  } /*if (f2py_success) of maxnd*/
  /* End of cleaning variable maxnd */
  if((PyObject *)capi_xw_tmp!=xw_capi) {
    Py_XDECREF(capi_xw_tmp); }
  }  /*if (capi_xw_tmp == NULL) ... else of xw*/
  /* End of cleaning variable xw */
  if((PyObject *)capi_ak_tmp!=ak_capi) {
    Py_XDECREF(capi_ak_tmp); }
  }  /*if (capi_ak_tmp == NULL) ... else of ak*/
  /* End of cleaning variable ak */
  } /*CHECKSCALAR(len(xtemp)>=maxeq)*/
  } /*if (f2py_success) of maxeq*/
  /* End of cleaning variable maxeq */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  if((PyObject *)capi_xtemp_tmp!=xtemp_capi) {
    Py_XDECREF(capi_xtemp_tmp); }
  }  /*if (capi_xtemp_tmp == NULL) ... else of xtemp*/
  /* End of cleaning variable xtemp */
  } /*if (f2py_success) of t1*/
  /* End of cleaning variable t1 */
  } /*if (f2py_success) of t2*/
  /* End of cleaning variable t2 */
  } /*if (f2py_success) of tt*/
  /* End of cleaning variable tt */
  } /*if (f2py_success) of node*/
  /* End of cleaning variable node */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of vel123 *******************************/

/********************************** intrp123 **********************************/
static char doc_f2py_rout_ftracking_intrp123[] = "\
Function signature:\n\
  intrp123(neq,node,xtemp,xw,dn,djac,[maxeq,maxnd])\n\
Required arguments:\n"
"  neq : input int\n"
"  node : input int\n"
"  xtemp : input rank-1 array('d') with bounds (maxeq)\n"
"  xw : input rank-2 array('d') with bounds (maxeq,maxnd)\n"
"  dn : input rank-1 array('d') with bounds (maxnd)\n"
"  djac : input float\n"
"Optional arguments:\n"
"  maxeq := len(xtemp) input int\n"
"  maxnd := shape(xw,1) input int";
/* extern void F_FUNC(intrp123,INTRP123)(int*,int*,int*,int*,double*,double*,double*,double*); */
static PyObject *f2py_rout_ftracking_intrp123(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int maxeq = 0;
  PyObject *maxeq_capi = Py_None;
  int maxnd = 0;
  PyObject *maxnd_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  int node = 0;
  PyObject *node_capi = Py_None;
  double *xtemp = NULL;
  npy_intp xtemp_Dims[1] = {-1};
  const int xtemp_Rank = 1;
  PyArrayObject *capi_xtemp_tmp = NULL;
  int capi_xtemp_intent = 0;
  PyObject *xtemp_capi = Py_None;
  double *xw = NULL;
  npy_intp xw_Dims[2] = {-1, -1};
  const int xw_Rank = 2;
  PyArrayObject *capi_xw_tmp = NULL;
  int capi_xw_intent = 0;
  PyObject *xw_capi = Py_None;
  double *dn = NULL;
  npy_intp dn_Dims[1] = {-1};
  const int dn_Rank = 1;
  PyArrayObject *capi_dn_tmp = NULL;
  int capi_dn_intent = 0;
  PyObject *dn_capi = Py_None;
  double djac = 0;
  PyObject *djac_capi = Py_None;
  static char *capi_kwlist[] = {"neq","node","xtemp","xw","dn","djac","maxeq","maxnd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OO:ftracking.intrp123",\
    capi_kwlist,&neq_capi,&node_capi,&xtemp_capi,&xw_capi,&dn_capi,&djac_capi,&maxeq_capi,&maxnd_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable node */
    f2py_success = int_from_pyobj(&node,node_capi,"ftracking.intrp123() 2nd argument (node) can't be converted to int");
  if (f2py_success) {
  /* Processing variable xtemp */
  ;
  capi_xtemp_intent |= F2PY_INTENT_IN;
  capi_xtemp_tmp = array_from_pyobj(PyArray_DOUBLE,xtemp_Dims,xtemp_Rank,capi_xtemp_intent,xtemp_capi);
  if (capi_xtemp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 3rd argument `xtemp' of ftracking.intrp123 to C/Fortran array" );
  } else {
    xtemp = (double *)(capi_xtemp_tmp->data);

  /* Processing variable djac */
    f2py_success = double_from_pyobj(&djac,djac_capi,"ftracking.intrp123() 6th argument (djac) can't be converted to double");
  if (f2py_success) {
  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ftracking.intrp123() 1st argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxeq */
  if (maxeq_capi == Py_None) maxeq = len(xtemp); else
    f2py_success = int_from_pyobj(&maxeq,maxeq_capi,"ftracking.intrp123() 1st keyword (maxeq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xtemp)>=maxeq,"len(xtemp)>=maxeq","1st keyword maxeq","intrp123:maxeq=%d",maxeq) {
  /* Processing variable xw */
  xw_Dims[0]=maxeq;
  capi_xw_intent |= F2PY_INTENT_IN;
  capi_xw_tmp = array_from_pyobj(PyArray_DOUBLE,xw_Dims,xw_Rank,capi_xw_intent,xw_capi);
  if (capi_xw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 4th argument `xw' of ftracking.intrp123 to C/Fortran array" );
  } else {
    xw = (double *)(capi_xw_tmp->data);

  /* Processing variable maxnd */
  if (maxnd_capi == Py_None) maxnd = shape(xw,1); else
    f2py_success = int_from_pyobj(&maxnd,maxnd_capi,"ftracking.intrp123() 2nd keyword (maxnd) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xw,1)==maxnd,"shape(xw,1)==maxnd","2nd keyword maxnd","intrp123:maxnd=%d",maxnd) {
  /* Processing variable dn */
  dn_Dims[0]=maxnd;
  capi_dn_intent |= F2PY_INTENT_IN;
  capi_dn_tmp = array_from_pyobj(PyArray_DOUBLE,dn_Dims,dn_Rank,capi_dn_intent,dn_capi);
  if (capi_dn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ftracking_error,"failed in converting 5th argument `dn' of ftracking.intrp123 to C/Fortran array" );
  } else {
    dn = (double *)(capi_dn_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&maxeq,&maxnd,&neq,&node,xtemp,xw,dn,&djac);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_dn_tmp!=dn_capi) {
    Py_XDECREF(capi_dn_tmp); }
  }  /*if (capi_dn_tmp == NULL) ... else of dn*/
  /* End of cleaning variable dn */
  } /*CHECKSCALAR(shape(xw,1)==maxnd)*/
  } /*if (f2py_success) of maxnd*/
  /* End of cleaning variable maxnd */
  if((PyObject *)capi_xw_tmp!=xw_capi) {
    Py_XDECREF(capi_xw_tmp); }
  }  /*if (capi_xw_tmp == NULL) ... else of xw*/
  /* End of cleaning variable xw */
  } /*CHECKSCALAR(len(xtemp)>=maxeq)*/
  } /*if (f2py_success) of maxeq*/
  /* End of cleaning variable maxeq */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  } /*if (f2py_success) of djac*/
  /* End of cleaning variable djac */
  if((PyObject *)capi_xtemp_tmp!=xtemp_capi) {
    Py_XDECREF(capi_xtemp_tmp); }
  }  /*if (capi_xtemp_tmp == NULL) ... else of xtemp*/
  /* End of cleaning variable xtemp */
  } /*if (f2py_success) of node*/
  /* End of cleaning variable node */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of intrp123 ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"foo",-1,{{-1}},0,(char *)F_FUNC(foo,FOO),(f2py_init_func)f2py_rout_ftracking_foo,doc_f2py_rout_ftracking_foo},
  {"foo2",-1,{{-1}},0,(char *)F_FUNC(foo2,FOO2),(f2py_init_func)f2py_rout_ftracking_foo2,doc_f2py_rout_ftracking_foo2},
  {"sspt123",-1,{{-1}},0,(char *)F_FUNC(sspt123,SSPT123),(f2py_init_func)f2py_rout_ftracking_sspt123,doc_f2py_rout_ftracking_sspt123},
  {"eltrak123",-1,{{-1}},0,(char *)F_FUNC(eltrak123,ELTRAK123),(f2py_init_func)f2py_rout_ftracking_eltrak123,doc_f2py_rout_ftracking_eltrak123},
  {"dn_check",-1,{{-1}},0,(char *)F_FUNC_US(dn_check,DN_CHECK),(f2py_init_func)f2py_rout_ftracking_dn_check,doc_f2py_rout_ftracking_dn_check},
  {"rkck_pt",-1,{{-1}},0,(char *)F_FUNC_US(rkck_pt,RKCK_PT),(f2py_init_func)f2py_rout_ftracking_rkck_pt,doc_f2py_rout_ftracking_rkck_pt},
  {"vel123",-1,{{-1}},0,(char *)F_FUNC(vel123,VEL123),(f2py_init_func)f2py_rout_ftracking_vel123,doc_f2py_rout_ftracking_vel123},
  {"intrp123",-1,{{-1}},0,(char *)F_FUNC(intrp123,INTRP123),(f2py_init_func)f2py_rout_ftracking_intrp123,doc_f2py_rout_ftracking_intrp123},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initftracking(void) {
  int i;
  PyObject *m,*d, *s;
  /*mwf debug*/
  printf("ftrackingmodule before Py_InitModule\n");
  m = ftracking_module = Py_InitModule("ftracking", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  /*mwf debug*/
  printf("ftrackingmodule after Py_InitModule before import array\n");
  /*mwf debug*/
#ifdef NO_IMPORT_ARRAY
  printf("ftrackingmodule says NO_IMPORT_ARRAY defined before import array call\n");
#endif
#ifdef PY_ARRAY_UNIQUE_SYMBOL
  printf("ftrackingmodule says PY_ARRAY_UNIQUE_SYMBOL defined before import array call\n");
#endif
  import_array();
  /*mwf debug*/
  printf("ftrackingmodule after import array\n");
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module ftracking (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'ftracking' is auto-generated with f2py (version:2_5972).\nFunctions:\n"
"  foo(a,b,nd=len(a),n=shape(b,0),m=shape(b,1))\n"
"  foo2(xg,neq=shape(xg,0),nnp=shape(xg,1))\n"
"  sspt123(nnp,nel,nnde,neq,npt,ibf,lu_o,atol,rtol,sf,dn_safe,xg,ie,nlrl,lrl,vtl2g,vt1e,x_i,t_i,tpt,mpt,idpt,xpt,maxeq=3)\n"
"  eltrak123(neq,node,ipt,t1,t2,deq,atol,rtol,sf,dn_safe,xw,vt1w,vt2w,t,dt0,sdt,xs,ak1,ak2,ak3,ak4,ak5,ak6,xtemp,xout5,xout4,xerr,dn_s,dn,idsdt,xpt,tpt,i1,i2,i3,maxeq=shape(xw,0),maxnd=shape(xw,1),maxpt=len(tpt))\n"
"  dn_check(node,neq,dl,atol,dn,i1,i2,i3,maxnd=len(dn))\n"
"  rkck_pt(neq,node,t,dt,t1,t2,xw,vt1w,vt2w,xs,ak1,ak2,ak3,ak4,ak5,ak6,xtemp,xout5,xout4,xerr,dn_s,maxeq=shape(xw,0),maxnd=shape(xw,1))\n"
"  vel123(neq,node,xtemp,tt,t1,t2,xw,vt1w,vt2w,ak,dn,maxeq=len(xtemp),maxnd=shape(xw,1))\n"
"  intrp123(neq,node,xtemp,xw,dn,djac,maxeq=len(xtemp),maxnd=shape(xw,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  ftracking_error = PyErr_NewException ("ftracking.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"ftracking");
#endif

}
#ifdef __cplusplus
}
#endif
