#!/bin/bash



if [ $# -eq 2 ]; then
  geofile=$1
  maxhe=$2
else
  echo "Wrong input"
  echo "Usage: generate_gmsh_mesh <geo-file> <scale>" 
  exit
fi 
 
rm -f gmsh.mesh log
time gmsh $geofile -v 10 -3 -o gmsh.mesh  -format mesh  -clmax $maxhe -clscale $maxhe | tee log 

echo "maxhe=$maxhe" >> log

if [ -f gmsh.mesh ]; then
  nodes=`head -5 gmsh.mesh | tail -1`
  dir=mesh`echo $nodes`
  mkdir -p $dir
  cd $dir
  mv ../gmsh.mesh .
  mv ../log gmsh.log

  grep ille gmsh.log
  echo =============================
  grep ille gmsh.log | grep -v no

  gmsh2tetgen_mprans_withtags gmsh.mesh 
  cp mesh.vtk ../$dir.vtk
  echo =============================
  ls -lhatr mesh.*
  cp mesh.ele mesh_save.ele
  cp mesh.node mesh_save.node
  tetgen -Vfeen mesh.ele
  echo =============================
  ls -lhatr mesh.*
  mv mesh.1.ele mesh.ele
  mv mesh.1.node mesh.node
  mv mesh.1.face mesh.face
  mv mesh.1.neigh mesh.neigh
  mv mesh.1.edge mesh.edge
  echo =============================
  ls -lhatr mesh.*
  grep ille gmsh.log
  echo =============================
  grep ille gmsh.log | grep -v no
  echo =============================
  echo $nodes nodes 
  echo =============================
fi
