#!/usr/bin/env python
from proteus.InputTranslators import Ipars
import optparse

usage = "usage: %prog [option] iparseinput_file"
parser = optparse.OptionParser(usage=usage)
(opt,args) = parser.parse_args()
if len(args) != 1:
   raise RuntimeError("Must specify single input file")
ipars = Ipars(args[0])

