#!/usr/bin/env python
import sys,os,pexpect

np=2
PROTEUS = os.getenv('PROTEUS')
PROTEUS_PYTHON = os.getenv('PROTEUS_PYTHON')
PATH = os.getenv('PATH')
LD_LIBRARY_PATH = os.getenv('LD_LIBRARY_PATH')
DYLD_LIBRARY_PATH = os.getenv('DYLD_LIBRARY_PATH')
print sys.argv
pcmd="mpirun -n %(np)i %(PROTEUS_PYTHON)s %(PYTHON_SCRIPT)s" % {"np":np,
                                                                "PROTEUS":PROTEUS,
                                                                "PROTEUS_PYTHON":PROTEUS_PYTHON,
                                                                "PYTHON_SCRIPT":sys.argv[1]}
child = pexpect.spawn('/bin/bash',timeout='5')
child.logfile = sys.stdout
child.sendline("export PATH="+`PATH`)
child.sendline("export LD_LIBRARY_PATH="+`LD_LIBRARY_PATH`)
child.sendline("export DYLD_LIBRARY_PATH="+`DYLD_LIBRARY_PATH`)
child.sendline("rehash")
child.sendline(pcmd)
child.expect(["PEXPECT_EXIT",pexpect.EOF,pexpect.TIMEOUT],timeout=10*60)
child.sendline("exit")
child.close()
